import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Link, useParams, useLocation } from "wouter";
import { formatAuthors } from "@/lib/utils";
import { apiRequest } from "@/lib/queryClient";
import { useAuth } from "@/components/auth/ProtectedRoute";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  HiArrowLeft,
  HiDownload,
  HiExternalLink,
  HiUser,
  HiBookOpen,
  HiCalendar,
  HiDocumentText,
  HiLink,
  HiBookmark,
  HiOutlineBookmark,
} from "react-icons/hi";
import { Helmet } from "react-helmet";
import DOMPurify from "dompurify";

/** Convert simple markdown to sanitized HTML */
function markdownToSafeHtml(text: string): string {
  const html = text
    .replace(/###\s/g, '<h4 class="text-lg font-semibold mt-6 mb-3 text-neutral-800">')
    .replace(/####\s/g, '<h5 class="text-base font-medium mt-4 mb-2 text-neutral-800">')
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n\n/g, '</p><p class="mb-4">')
    .replace(/^/, '<p class="mb-4">')
    .replace(/$/, "</p>");
  return DOMPurify.sanitize(html);
}
import { useEffect, useMemo } from "react";
import { StudyInfoPanel } from "@/components/StudyInfoPanel";
import SiteHeader from "@/components/layout/SiteHeader";
import Footer from "@/components/layout/Footer";
import {
  EDITORIAL_TEAM,
  abstractExcerpt,
  formatLongDate,
  isoDate,
  realContent,
  studyDescription,
  studyJsonLd,
  studyPageTitle,
  studySourceLink,
  studyUpdatedAt,
  withoutPlaceholders,
} from "@shared/seo-markup";

const SITE_URL = "https://hydrogenstudies.com";

interface Study {
  id: number;
  title: string;
  plainLanguageTitle?: string;
  plain_language_title?: string;
  slug?: string;
  abstract: string;
  authors: string;
  journal: string;
  category: string;
  publishDate?: string;
  journalPublishDate?: string;
  year?: number;
  publishYear?: number;
  doi?: string;
  url?: string;
  pdfUrl?: string;
  pdf_url?: string;
  imageUrl?: string;
  image_url?: string;
  imageAlt?: string;
  image_alt?: string;
  autoGeneratedImage?: boolean;
  auto_generated_image?: boolean;
  methods?: string;
  results?: string;
  conclusion?: string;
  citations?: number;
  citationCount?: number;
  citation_count?: number;
  viewCount?: number;
  view_count?: number;
  authorAffiliations?: string;
  author_affiliations?: string;
  fundingSources?: string;
  funding_sources?: string;
  ethicalApproval?: string;
  ethical_approval?: string;
  trialRegistration?: string;
  trial_registration?: string;
  statisticalMethods?: string;
  statistical_methods?: string;
  supplementaryMaterials?: string;
  supplementary_materials?: string;
  fullText?: string;
  full_text?: string;
  fullTextHtml?: string;
  full_text_html?: string;
  sourcePlatform?: string;
  source_platform?: string;
  // Our own summary fields (same sections the bot renderer shows).
  tldr?: string | null;
  keyFinding?: string | null;
  plainSummary?: string | null;
  summary100Words?: string | null;
  summary50Words?: string | null;
  practicalTakeaway?: string | null;
  howToApply?: string | null;
  // SEO / identifiers / timestamps
  pmid?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  lastModified?: string | null;
  createdAt?: string | null;
  keywords?: string[] | null;
  ogImage?: string | null;
}

// Shape returned by GET /api/explorer/study-connections
interface StudyConnection {
  source: number;
  target: number;
  strength: number;
  type: string;
}

// Map known data-source platforms to their attribution link-back URLs
const SOURCE_ATTRIBUTION_LINKS: Record<string, string> = {
  "semantic scholar": "https://www.semanticscholar.org",
  semanticscholar: "https://www.semanticscholar.org",
  "europe pmc": "https://europepmc.org",
  europepmc: "https://europepmc.org",
  biorxiv: "https://www.biorxiv.org",
  medrxiv: "https://www.medrxiv.org",
  crossref: "https://www.crossref.org",
};

export default function SEOStudyPage() {
  const params = useParams();
  const [location, navigate] = useLocation();

  // Determine if we're accessing by slug or ID
  const identifier = params.slug || params.id;
  // Check if identifier looks like a numeric ID
  const isNumericId = identifier && /^\d+$/.test(identifier);
  const isSlugRoute = !isNumericId;

  // Fetch study data based on route type
  const {
    data: rawStudy,
    isLoading,
    error,
  } = useQuery<Study>({
    queryKey: isNumericId
      ? [`/api/studies/${identifier}`]
      : [`/api/studies/slug/${identifier}`],
    enabled: !!identifier,
  });
  // CLAUDE.md: empty fields never render; pipeline sentinels such as
  // key_finding = "__no_content__" (and N/A-style fillers) never reach the
  // DOM. Null every placeholder string once so all `{field && …}` guards skip.
  const study = useMemo(
    () => (rawStudy ? withoutPlaceholders(rawStudy) : undefined),
    [rawStudy],
  );

  // Redirect to slug-based URL if we loaded by ID and have a slug
  useEffect(() => {
    if (
      study &&
      study.slug &&
      !isSlugRoute &&
      !location.includes("/study/id/")
    ) {
      navigate(`/study/${study.slug}`, { replace: true });
    }
  }, [study, isSlugRoute, location, navigate]);

  // Citation-connections panel (enh-10): fetch related studies for this id.
  // The default query fn appends studyId as a query param. Degrades to an
  // empty/undefined list on error so the panel simply renders nothing.
  const { data: connections } = useQuery<StudyConnection[]>({
    queryKey: ["/api/explorer/study-connections", { studyId: study?.id }],
    enabled: !!study?.id,
  });
  const relatedStudyIds = Array.from(
    new Set(
      (connections ?? []).map((c) =>
        c.source === study?.id ? c.target : c.source,
      ),
    ),
  )
    .filter((id) => id !== study?.id)
    .slice(0, 8);

  // Save/bookmark (enh-5): only meaningful for authenticated users.
  const queryClient = useQueryClient();
  const { isAuthenticated } = useAuth();
  const { data: savedData } = useQuery<{ savedStudyIds: number[] }>({
    queryKey: ["/api/me/saved-studies"],
    enabled: isAuthenticated,
  });
  const isSaved = !!(
    study?.id && savedData?.savedStudyIds?.includes(study.id)
  );
  const saveMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await apiRequest("POST", `/api/me/save-study/${id}`);
      return (await res.json()) as { saved: boolean };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/me/saved-studies"] });
    },
  });

  if (isLoading) {
    return (
      <>
        <SiteHeader />
        <div className="min-h-screen bg-white py-12">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <div className="h-6 bg-neutral-200 rounded w-48 mb-6 animate-pulse"></div>
              <div className="h-10 bg-neutral-200 rounded w-full mb-4 animate-pulse"></div>
              <div className="flex space-x-4 mb-6">
                <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
                <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
              </div>
              <div className="space-y-2 mb-8">
                <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
                <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
                <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
                <div className="h-4 bg-neutral-200 rounded w-3/4 animate-pulse"></div>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  }

  if (error || !study) {
    return (
      <>
        <SiteHeader />
        <div className="min-h-screen bg-white py-12">
          <div className="container mx-auto px-4 text-center">
            <Card className="max-w-md mx-auto">
              <CardContent className="pt-6 pb-6">
                <h1 className="text-xl font-bold mb-4">Study Not Found</h1>
                <p className="text-neutral-600 mb-6">
                  {error instanceof Error
                    ? error.message
                    : "We couldn't find the study you're looking for. It may have been removed or the link is incorrect."}
                </p>
                <Link href="/recent-studies">
                  <Button>
                    <HiArrowLeft className="mr-2" />
                    Browse Recent Studies
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </div>
        </div>
      </>
    );
  }

  // Get plain language title for SEO
  const plainTitle = study.plainLanguageTitle || study.plain_language_title;
  // Title, description and JSON-LD come from shared/seo-markup — the bot
  // renderer (seo-bot-middleware buildStudyMeta) uses the same helpers.
  const pageTitle = studyPageTitle({ ...study, plainLanguageTitle: plainTitle });
  const metaDescription = studyDescription(study, 160);

  // Generate SEO-friendly URL for canonical link
  const canonicalUrl = study.slug
    ? `${SITE_URL}/study/${study.slug}`
    : `${SITE_URL}/study/id/${study.id}`;
  const rawImage = study.ogImage || study.imageUrl || study.image_url || "/logo.png";
  const absoluteImage = /^https?:\/\//i.test(rawImage)
    ? rawImage
    : `${SITE_URL}${rawImage.startsWith("/") ? "" : "/"}${rawImage}`;
  // No `abstract` field and a ≤300-char description (publisher copyright).
  const studyLd = studyJsonLd(
    { ...study, plainLanguageTitle: plainTitle },
    { canonical: canonicalUrl, siteUrl: SITE_URL, image: absoluteImage },
  );

  // CLAUDE.md: ≤300-char abstract excerpt + a link to PubMed/DOI — never the
  // full abstract.
  const excerpt = abstractExcerpt(study.abstract);
  const sourceLink = studySourceLink(study);
  const updatedAt = studyUpdatedAt(study);
  const summaryText =
    realContent(study.plainSummary) ||
    realContent(study.summary100Words) ||
    realContent(study.summary50Words);

  // Data-source attribution (Semantic Scholar requires this; Europe PMC/bioRxiv request it)
  const sourcePlatform = study.sourcePlatform || study.source_platform;
  const sourceAttributionUrl = sourcePlatform
    ? SOURCE_ATTRIBUTION_LINKS[sourcePlatform.trim().toLowerCase()]
    : undefined;

  return (
    <>
      <SiteHeader />

      <Helmet>
        <title>{pageTitle}</title>
        <meta name="description" content={metaDescription} />
        <meta property="og:title" content={pageTitle} />
        <meta property="og:description" content={metaDescription} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={canonicalUrl} />
        <link rel="canonical" href={canonicalUrl} />

        {/* Article-specific meta tags */}
        <meta name="article:author" content={formatAuthors(study.authors)} />
        <meta
          name="article:published_time"
          content={study.journalPublishDate || study.publishDate}
        />
        <meta name="article:section" content={study.category} />

        {/* Twitter Card */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={pageTitle} />
        <meta name="twitter:description" content={metaDescription} />

        {/* Structured data — identical to the bot renderer's (shared studyJsonLd) */}
        <script type="application/ld+json">{JSON.stringify(studyLd)}</script>
      </Helmet>

      <section className="bg-white py-8 md:py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-7xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Main Content Column */}
              <div className="lg:col-span-2">
                {/* Breadcrumb */}
                <nav aria-label="Breadcrumb" className="mb-6">
                  <ol className="flex items-center text-sm text-neutral-500">
                    <li className="inline-flex items-center">
                      <Link href="/">
                        <span className="hover:text-primary cursor-pointer">
                          Home
                        </span>
                      </Link>
                      <span className="mx-2" aria-hidden="true">
                        /
                      </span>
                    </li>
                    <li className="inline-flex items-center">
                      <Link href="/categories">
                        <span className="hover:text-primary cursor-pointer">
                          Categories
                        </span>
                      </Link>
                      <span className="mx-2" aria-hidden="true">
                        /
                      </span>
                    </li>
                    {study.category && (
                      <li className="inline-flex items-center">
                        <Link
                          href={`/category/${encodeURIComponent(study.category.toLowerCase())}`}
                        >
                          <span className="hover:text-primary cursor-pointer">
                            {study.category}
                          </span>
                        </Link>
                        <span className="mx-2" aria-hidden="true">
                          /
                        </span>
                      </li>
                    )}
                    <li
                      className="inline-flex items-center"
                      aria-current="page"
                    >
                      <span className="text-neutral-800">Study</span>
                    </li>
                  </ol>
                </nav>

                {/* SEO-Optimized Study Header */}
                <header className="mb-6 md:mb-8">
                  {/* Category and date */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 mb-4">
                    {study.category && (
                      <Badge
                        variant="secondary"
                        className="bg-primary/10 text-primary hover:bg-primary/15 w-fit"
                      >
                        {study.category}
                      </Badge>
                    )}
                    {(study.year || study.publishYear) && (
                      <time
                        dateTime={(study.year || study.publishYear)?.toString()}
                        className="text-neutral-500 flex items-center text-sm"
                      >
                        <HiCalendar
                          className="mr-1 w-4 h-4"
                          aria-hidden="true"
                        />
                        {study.year || study.publishYear}
                      </time>
                    )}
                  </div>

                  {/* SEO-optimized title structure: Plain language as H1, original as H2 */}
                  {plainTitle ? (
                    <div className="mb-4">
                      <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 leading-tight text-primary">
                        {plainTitle.replace(/["""]/g, "")}
                      </h1>
                      <h2 className="text-lg sm:text-xl md:text-2xl font-medium text-neutral-700 leading-snug">
                        {study.title}
                      </h2>
                    </div>
                  ) : (
                    <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-4 leading-tight">
                      {study.title}
                    </h1>
                  )}

                  {/* Author/reviewer + date line (CLAUDE.md) — same copy as
                      the bot renderer's renderStudy byline. */}
                  <p className="byline text-sm text-neutral-600 mb-3">
                    Summary by{" "}
                    <Link href="/methodology" className="underline hover:text-primary">
                      {EDITORIAL_TEAM}
                    </Link>
                    {updatedAt && (
                      <>
                        {" "}· Updated{" "}
                        <time dateTime={isoDate(updatedAt)}>{formatLongDate(updatedAt)}</time>
                      </>
                    )}
                  </p>

                  {/* Study metadata */}
                  <div className="space-y-2 md:space-y-0 md:flex md:flex-wrap md:items-center text-neutral-600 text-sm">
                    <div className="flex items-center">
                      <HiUser
                        className="mr-2 w-4 h-4 flex-shrink-0"
                        aria-hidden="true"
                      />
                      <span className="line-clamp-1">{formatAuthors(study.authors)}</span>
                    </div>
                    <div className="flex items-center md:ml-6">
                      <HiBookOpen
                        className="mr-2 w-4 h-4 flex-shrink-0"
                        aria-hidden="true"
                      />
                      <span className="line-clamp-1">{study.journal}</span>
                    </div>
                    <div className="flex items-center md:ml-6">
                      <HiDocumentText
                        className="mr-2 w-4 h-4 flex-shrink-0"
                        aria-hidden="true"
                      />
                      <span>
                        {study.citations ||
                          study.citationCount ||
                          study.citation_count ||
                          0}{" "}
                        citations
                      </span>
                    </div>
                  </div>
                </header>

                {/* Study Content */}
                <article className="bg-white border border-neutral-200 rounded-lg md:rounded-xl shadow-sm mb-6 md:mb-10">
                  <div className="p-4 sm:p-6 md:p-8">
                    {/* Study Image */}
                    {(study.imageUrl || study.image_url) &&
                      !(study.imageUrl || study.image_url)?.includes(
                        "placehold.co",
                      ) &&
                      !(study.imageUrl || study.image_url)?.includes(
                        "placeholder",
                      ) && (
                        <section className="mb-8">
                          <figure className="rounded-lg overflow-hidden shadow-md">
                            <img
                              src={
                                (study.imageUrl || study.image_url)?.startsWith(
                                  "http",
                                )
                                  ? study.imageUrl || study.image_url
                                  : `/${study.imageUrl || study.image_url}`
                              }
                              alt={
                                study.imageAlt ||
                                study.image_alt ||
                                `Scientific visualization for ${study.title}`
                              }
                              loading="lazy"
                              decoding="async"
                              className="w-full h-auto max-h-96 object-cover"
                              onError={(e) => {
                                const target = e.target as HTMLImageElement;
                                target.style.display = "none";
                              }}
                            />
                            <figcaption className="p-4 bg-neutral-50 border-t">
                              <p className="text-sm text-neutral-600 italic">
                                {study.autoGeneratedImage ||
                                study.auto_generated_image
                                  ? "AI-generated scientific visualization representing hydrogen mechanisms and therapeutic effects described in this study"
                                  : "Scientific illustration related to hydrogen research methodology and findings"}
                              </p>
                            </figcaption>
                          </figure>
                        </section>
                      )}

                    {/* Our own summary — same sections, same order as the
                        bot renderer (renderStudy). Placeholders were nulled
                        above, so empty/sentinel fields never render. */}
                    {study.tldr && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">TL;DR</h2>
                        <p className="text-neutral-700 leading-relaxed">{study.tldr}</p>
                      </section>
                    )}
                    {study.keyFinding && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">Key Finding</h2>
                        <p className="text-neutral-700 leading-relaxed">{study.keyFinding}</p>
                      </section>
                    )}
                    {summaryText && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">Summary</h2>
                        <p className="text-neutral-700 leading-relaxed">{summaryText}</p>
                      </section>
                    )}
                    {study.practicalTakeaway && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">Practical Takeaway</h2>
                        <p className="text-neutral-700 leading-relaxed">{study.practicalTakeaway}</p>
                      </section>
                    )}
                    {study.howToApply && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">How to Apply This Research</h2>
                        <p className="text-neutral-700 leading-relaxed">{study.howToApply}</p>
                      </section>
                    )}

                    {/* Abstract excerpt — ≤300 chars + link to the source.
                        Never the full abstract (publisher copyright). */}
                    {(excerpt || sourceLink) && (
                      <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-4">Abstract (excerpt)</h2>
                        {excerpt && (
                          <p className="text-neutral-700 leading-relaxed">{excerpt}</p>
                        )}
                        {sourceLink && (
                          <p className="mt-3">
                            <a
                              href={sourceLink.href}
                              target="_blank"
                              rel="noopener"
                              className="text-primary underline hover:no-underline inline-flex items-center"
                            >
                              {sourceLink.label}
                              <HiExternalLink className="ml-1 w-4 h-4" aria-hidden="true" />
                            </a>
                          </p>
                        )}
                      </section>
                    )}

                    {/* Enhanced Methods, Results, Conclusion sections */}
                    {study.methods && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Methods
                        </h3>
                        <div className="text-neutral-700 leading-relaxed prose prose-neutral max-w-none">
                          <div
                            dangerouslySetInnerHTML={{
                              __html: markdownToSafeHtml(study.methods),
                            }}
                          />
                        </div>
                      </section>
                    )}

                    {study.results && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Results
                        </h3>
                        <div className="text-neutral-700 leading-relaxed prose prose-neutral max-w-none">
                          <div
                            dangerouslySetInnerHTML={{
                              __html: markdownToSafeHtml(study.results),
                            }}
                          />
                        </div>
                      </section>
                    )}

                    {study.conclusion && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Plain-Language Summary
                        </h3>
                        <div className="text-neutral-700 leading-relaxed bg-neutral-50 p-4 rounded-lg border-l-4 border-primary">
                          <p>{study.conclusion}</p>
                        </div>
                      </section>
                    )}

                    {/* Additional Research Information Sections */}
                    {(study.authorAffiliations ||
                      study.author_affiliations) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Author Affiliations
                        </h3>
                        <div className="text-neutral-700 leading-relaxed bg-teal-50 p-4 rounded-lg border-l-4 border-teal-500">
                          <p>
                            {study.authorAffiliations ||
                              study.author_affiliations}
                          </p>
                        </div>
                      </section>
                    )}

                    {(study.fundingSources || study.funding_sources) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Funding Sources
                        </h3>
                        <div className="text-neutral-700 leading-relaxed bg-green-50 p-4 rounded-lg border-l-4 border-green-500">
                          <p>{study.fundingSources || study.funding_sources}</p>
                        </div>
                      </section>
                    )}

                    {(study.statisticalMethods ||
                      study.statistical_methods) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Statistical Methods
                        </h3>
                        <div className="text-neutral-700 leading-relaxed">
                          <p>
                            {study.statisticalMethods ||
                              study.statistical_methods}
                          </p>
                        </div>
                      </section>
                    )}

                    {(study.ethicalApproval || study.ethical_approval) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Ethical Approval
                        </h3>
                        <div className="text-neutral-700 leading-relaxed bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-500">
                          <p>
                            {study.ethicalApproval || study.ethical_approval}
                          </p>
                        </div>
                      </section>
                    )}

                    {(study.trialRegistration || study.trial_registration) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Trial Registration
                        </h3>
                        <div className="text-neutral-700 leading-relaxed">
                          <p>
                            {study.trialRegistration ||
                              study.trial_registration}
                          </p>
                        </div>
                      </section>
                    )}

                    {(study.supplementaryMaterials ||
                      study.supplementary_materials) && (
                      <section className="mb-8">
                        <h3 className="text-xl font-semibold mb-4 text-primary">
                          Supplementary Materials
                        </h3>
                        <div className="text-neutral-700 leading-relaxed">
                          <p>
                            {study.supplementaryMaterials ||
                              study.supplementary_materials}
                          </p>
                        </div>
                      </section>
                    )}

                    {/* The former "Full Research Text" section (up to 8,000
                        chars of publisher full text) is removed: same
                        copyright rule as abstracts. The DOI / PDF / source
                        buttons below link readers to the original. */}

                    {/* Action buttons */}
                    <div className="flex flex-wrap gap-3 pt-6 border-t border-neutral-200">
                      {/* Save/bookmark (enh-5) */}
                      {isAuthenticated ? (
                        <Button
                          variant={isSaved ? "default" : "outline"}
                          size="sm"
                          onClick={() => saveMutation.mutate(study.id)}
                          disabled={saveMutation.isPending}
                          aria-pressed={isSaved}
                          aria-label={
                            isSaved
                              ? "Remove this study from your saved list"
                              : "Save this study to your list"
                          }
                        >
                          {isSaved ? (
                            <HiBookmark className="mr-2 w-4 h-4" />
                          ) : (
                            <HiOutlineBookmark className="mr-2 w-4 h-4" />
                          )}
                          {isSaved ? "Saved" : "Save"}
                        </Button>
                      ) : (
                        <Link
                          href={`/login?redirect=${encodeURIComponent(location)}`}
                        >
                          <Button
                            variant="outline"
                            size="sm"
                            aria-label="Sign in to save this study"
                          >
                            <HiOutlineBookmark className="mr-2 w-4 h-4" />
                            Sign in to save
                          </Button>
                        </Link>
                      )}
                      {study.doi && (
                        <Button variant="outline" size="sm" asChild>
                          <a
                            href={`https://doi.org/${study.doi}`}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <HiExternalLink className="mr-2 w-4 h-4" />
                            View DOI
                          </a>
                        </Button>
                      )}
                      {(study.pdfUrl || study.pdf_url) && (
                        <Button variant="outline" size="sm" asChild>
                          <a
                            href={study.pdfUrl || study.pdf_url}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <HiDownload className="mr-2 w-4 h-4" />
                            Download PDF
                          </a>
                        </Button>
                      )}
                      {study.url && (
                        <Button variant="outline" size="sm" asChild>
                          <a
                            href={study.url}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <HiExternalLink className="mr-2 w-4 h-4" />
                            Original Source
                          </a>
                        </Button>
                      )}
                    </div>

                    {/* Data-source attribution */}
                    {sourcePlatform && (
                      <p className="mt-4 text-xs text-neutral-500">
                        Data provided by{" "}
                        {sourceAttributionUrl ? (
                          <a
                            href={sourceAttributionUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="underline hover:text-primary"
                          >
                            {sourcePlatform}
                          </a>
                        ) : (
                          sourcePlatform
                        )}
                      </p>
                    )}
                  </div>
                </article>

                {/* Citation-connections panel (enh-10) */}
                {relatedStudyIds.length > 0 && (
                  <section
                    className="mb-6 md:mb-10"
                    aria-labelledby="related-studies-heading"
                  >
                    <Card>
                      <CardContent className="p-4 sm:p-6">
                        <h2
                          id="related-studies-heading"
                          className="text-lg font-semibold mb-2 flex items-center"
                        >
                          <HiLink
                            className="mr-2 w-5 h-5 text-primary"
                            aria-hidden="true"
                          />
                          Related Studies
                        </h2>
                        <p className="text-sm text-neutral-500 mb-4">
                          Other studies connected to this research by topic and
                          shared terminology.
                        </p>
                        <ul className="space-y-2">
                          {relatedStudyIds.map((id) => (
                            <li key={id}>
                              <Link href={`/study/id/${id}`}>
                                <span className="text-primary hover:underline cursor-pointer text-sm inline-flex items-center">
                                  <HiExternalLink
                                    className="mr-2 w-4 h-4 flex-shrink-0"
                                    aria-hidden="true"
                                  />
                                  View related study #{id}
                                </span>
                              </Link>
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                  </section>
                )}

                {/* Back to studies */}
                <div className="text-center">
                  <Link href="/recent-studies">
                    <Button variant="outline">
                      <HiArrowLeft className="mr-2" />
                      Back to Recent Studies
                    </Button>
                  </Link>
                </div>
              </div>

              {/* Study Information Panel - Sidebar */}
              <div className="lg:col-span-1">
                <StudyInfoPanel study={study as any} relatedStudies={[]} />
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
