import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { HiArrowLeft, HiDownload, HiExternalLink, HiUser, HiBookOpen, HiCalendar, HiDocumentText, HiClipboardCheck, HiPhotograph } from "react-icons/hi";
import { Helmet } from "react-helmet";
import { useToast } from "@/hooks/use-toast";
import RelatedBlogs from "@/components/studies/related-blogs";
import JsonLd, { generateMedicalArticleSchema, generateBreadcrumbSchema } from "@/components/seo/JsonLd";

const StudyPage = () => {
  const { id } = useParams();
  const studyId = id ? parseInt(id) : 0; // Provide fallback to prevent NaN
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Define the Study type to match what's returned from the API
  interface Study {
    id: number;
    title: string;
    abstract: string;
    authors: string;
    journal: string;
    publishDate: string;
    category: string;
    methods?: string;
    results?: string;
    conclusion?: string;
    doi?: string;
    pdfUrl?: string;
    citationUrl?: string;
    imageUrl?: string;
    imageAlt?: string;
    autoGeneratedImage?: boolean;
    year?: number;
    studyType?: string;
    citations?: number;
    fullTextAvailable?: boolean;
  }

  const { data: study, isLoading, error } = useQuery<Study>({
    queryKey: [`/api/studies/${studyId}`],
  });
  
  // Create a fallback image URL for studies
  const fallbackImageUrl = "https://placehold.co/800x400/e2f3ff/003366?text=Hydrogen+Research+Visual";
  
  // Mutation for generating an AI image for this study
  const generateImageMutation = useMutation({
    mutationFn: async () => {
      const response = await fetch(`/api/image-generation/generate/${studyId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate image');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      if (data.success) {
        toast({
          title: "Image generated successfully",
          description: "A new scientific illustration has been created for this study.",
        });
        // Invalidate the study query to refresh the data with the new image
        queryClient.invalidateQueries({ queryKey: [`/api/studies/${studyId}`] });
      } else {
        toast({
          title: "Image generation failed",
          description: data.message || "Unable to generate image. Please try again later.",
          variant: "destructive"
        });
      }
    },
    onError: (error) => {
      toast({
        title: "Image generation failed",
        description: error instanceof Error ? error.message : "Unable to generate image. Please try again later.",
        variant: "destructive"
      });
    }
  });

  // Related studies query (same category)
  const { data: allStudies } = useQuery({
    queryKey: ["/api/studies"],
  });

  // Get related studies (same category, exclude current)
  const relatedStudies = allStudies && study
    ? allStudies
        .filter((s: any) => s.category === study.category && s.id !== studyId)
        .slice(0, 3)
    : [];

  if (isLoading) {
    return (
      <div className="min-h-screen bg-white py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="h-6 bg-neutral-200 rounded w-48 mb-6 animate-pulse"></div>
            <div className="h-10 bg-neutral-200 rounded w-full mb-4 animate-pulse"></div>
            <div className="flex space-x-4 mb-6">
              <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
              <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
            </div>
            <div className="space-y-2 mb-8">
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-3/4 animate-pulse"></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (error || !study) {
    return (
      <div className="min-h-screen bg-white py-12">
        <div className="container mx-auto px-4 text-center">
          <Card className="max-w-md mx-auto">
            <CardContent className="pt-6 pb-6">
              <h1 className="text-xl font-bold mb-4">Study Not Found</h1>
              <p className="text-neutral-600 mb-6">
                {error instanceof Error 
                  ? error.message 
                  : "We couldn't find the study you're looking for. It may have been removed or the ID is incorrect."}
              </p>
              <Link href="/recent">
                <Button>
                  <HiArrowLeft className="mr-2" />
                  Browse Recent Studies
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <>
      <Helmet>
        <title>{`Hydrogen Therapy Research: ${study.title} | Health Benefits & Effects`}</title>
        <meta name="description" content={`Explore research on ${study.category} showing how hydrogen therapy affects ${study.title.toLowerCase()}. View methodology, results, and scientific evidence.`} />
        <meta name="keywords" content={`hydrogen therapy, molecular hydrogen, ${study.category.toLowerCase()}, ${study.title.split(' ').slice(0, 5).join(' ').toLowerCase()}, health research`} />
        <link rel="canonical" href={`https://hydrogenstudies.com/study/${study.id}`} />
        
        {/* Open Graph tags for better social sharing */}
        <meta property="og:title" content={`Hydrogen Therapy Research: ${study.title}`} />
        <meta property="og:description" content={study.abstract ? study.abstract.substring(0, 200) + '...' : `Research on hydrogen therapy effects for ${study.category}.`} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`https://hydrogenstudies.com/study/${study.id}`} />
        <meta property="og:image" content={study.imageUrl || fallbackImageUrl} />
        
        {/* Twitter Card tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={`Hydrogen Research: ${study.title.substring(0, 60)}${study.title.length > 60 ? '...' : ''}`} />
        <meta name="twitter:description" content={study.abstract ? study.abstract.substring(0, 120) + '...' : `Research on hydrogen therapy effects for ${study.category}.`} />
        <meta name="twitter:image" content={study.imageUrl || fallbackImageUrl} />
      </Helmet>
      
      {/* JSON-LD Structured Data for Medical/Scientific Research */}
      <JsonLd 
        type="MedicalScholarlyArticle"
        data={generateMedicalArticleSchema(study)}
      />
      
      {/* Breadcrumb Schema */}
      <JsonLd 
        type="BreadcrumbList"
        data={generateBreadcrumbSchema([
          { name: 'Home', url: 'https://hydrogenstudies.com' },
          { name: 'Research Studies', url: 'https://hydrogenstudies.com/studies' },
          { name: study.category, url: `https://hydrogenstudies.com/category/${encodeURIComponent(study.category)}` },
          { name: study.title, url: `https://hydrogenstudies.com/study/${study.id}` }
        ])}
      />

      <section className="bg-white py-8 md:py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            {/* Breadcrumb */}
            <div className="flex items-center text-sm text-neutral-500 mb-6">
              <Link href="/">
                <span className="hover:text-primary cursor-pointer">Home</span>
              </Link>
              <span className="mx-2">/</span>
              <Link href="/categories">
                <span className="hover:text-primary cursor-pointer">Categories</span>
              </Link>
              <span className="mx-2">/</span>
              <Link href={`/category/${encodeURIComponent(study.category.toLowerCase())}`}>
                <span className="hover:text-primary cursor-pointer">{study.category}</span>
              </Link>
              <span className="mx-2">/</span>
              <span className="text-neutral-800">Study</span>
            </div>

            {/* Study Header */}
            <div className="mb-8">
              <div className="flex items-center mb-3">
                <Badge variant="secondary" className="bg-primary/10 text-primary hover:bg-primary/15">
                  {study.category}
                </Badge>
                {study.year && (
                  <span className="ml-4 text-neutral-500 flex items-center">
                    <HiCalendar className="mr-1" /> {study.year}
                  </span>
                )}
              </div>
              
              <h1 className="text-3xl md:text-4xl font-bold mb-4">{study.title}</h1>
              
              <div className="flex flex-wrap items-center text-neutral-600 gap-y-2">
                <span className="flex items-center mr-6">
                  <HiUser className="mr-1" /> {study.authors}
                </span>
                <span className="flex items-center mr-6">
                  <HiBookOpen className="mr-1" /> {study.journal}
                </span>
                <span className="flex items-center">
                  <HiDocumentText className="mr-1" /> {study.citations || "0"} citations
                </span>
              </div>
            </div>

            {/* Study Content */}
            <div className="bg-white border border-neutral-200 rounded-xl shadow-sm mb-10">
              <div className="p-6 md:p-8">
                <h2 className="text-xl font-semibold mb-4">Research Visualization</h2>
                {/* Study Image */}
                <div className="mb-8 rounded-lg overflow-hidden">
                  {/* Image with fallback */}
                  <div className="relative">
                    <img 
                      src={study.imageUrl ? study.imageUrl : fallbackImageUrl}
                      alt={`Visual representation of hydrogen research on ${study.title}`}
                      className="w-full h-auto object-cover shadow-sm rounded-md" 
                      onError={(e) => {
                        // Fallback if the image fails to load
                        const target = e.target as HTMLImageElement;
                        target.onerror = null; // Prevent infinite loop
                        target.src = fallbackImageUrl;
                      }}
                    />
                    
                    {/* Generate Image Button - Only show if image is missing or using fallback */}
                    {(!study.imageUrl || study.imageUrl === fallbackImageUrl) && (
                      <div className="absolute bottom-0 left-0 right-0 bg-neutral-800/70 p-3 flex justify-center">
                        <Button 
                          variant="secondary"
                          className="flex items-center gap-2 bg-white hover:bg-neutral-100"
                          onClick={() => generateImageMutation.mutate()}
                          disabled={generateImageMutation.isPending}
                        >
                          <HiPhotograph className="w-4 h-4" />
                          {generateImageMutation.isPending ? 'Generating...' : 'Generate Scientific Visual'}
                        </Button>
                      </div>
                    )}
                  </div>
                  
                  <div className="flex justify-between items-start mt-2">
                    <p className="text-xs text-neutral-500 italic">
                      {study.autoGeneratedImage ? 
                        "AI-generated visualization of the study's hydrogen mechanisms and effects" : 
                        "Visual representation of hydrogen effects related to this research"}
                    </p>
                    
                    {/* Image attribution if available */}
                    {study.imageAlt && (
                      <span className="text-xs text-neutral-400">
                        {study.imageAlt}
                      </span>
                    )}
                  </div>
                </div>

                <h2 className="text-xl font-semibold mb-4">Abstract</h2>
                <div className="prose max-w-none prose-neutral mb-8">
                  <p className="text-lg leading-relaxed">{study.abstract}</p>
                </div>

                {/* Methods Section */}
                {study.methods && (
                  <>
                    <Separator className="my-6" />
                    <h2 className="text-xl font-semibold mb-4">Methods</h2>
                    <div className="prose max-w-none prose-neutral mb-6">
                      <p>{study.methods}</p>
                    </div>
                  </>
                )}

                {/* Results Section */}
                {study.results && (
                  <>
                    <Separator className="my-6" />
                    <h2 className="text-xl font-semibold mb-4">Results</h2>
                    <div className="prose max-w-none prose-neutral mb-6">
                      <p>{study.results}</p>
                    </div>
                  </>
                )}

                {/* Conclusion Section */}
                {study.conclusion && (
                  <>
                    <Separator className="my-6" />
                    <h2 className="text-xl font-semibold mb-4">Conclusion</h2>
                    <div className="prose max-w-none prose-neutral mb-6">
                      <p>{study.conclusion}</p>
                    </div>
                  </>
                )}

                {/* Study Metadata */}
                <Separator className="my-6" />
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                  <div>
                    <h3 className="text-sm font-semibold text-neutral-500 uppercase mb-2">Publication Details</h3>
                    <ul className="space-y-2">
                      <li className="flex items-start">
                        <span className="font-semibold w-24">Journal:</span>
                        <span>{study.journal}</span>
                      </li>
                      <li className="flex items-start">
                        <span className="font-semibold w-24">Published:</span>
                        <span>{study.publishDate}</span>
                      </li>
                      {study.studyType && (
                        <li className="flex items-start">
                          <span className="font-semibold w-24">Study Type:</span>
                          <span>{study.studyType}</span>
                        </li>
                      )}
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-neutral-500 uppercase mb-2">Resources</h3>
                    <div className="space-y-3">
                      {study.doi && (
                        <a
                          href={`https://doi.org/${study.doi}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center text-primary hover:underline"
                        >
                          <HiExternalLink className="mr-2" />
                          View DOI Reference
                        </a>
                      )}
                      {study.pdfUrl && (
                        <a
                          href={study.pdfUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center text-primary hover:underline"
                        >
                          <HiDownload className="mr-2" />
                          Access Full PDF
                        </a>
                      )}
                      {study.citationUrl && (
                        <a
                          href={study.citationUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center text-primary hover:underline"
                        >
                          <HiDocumentText className="mr-2" />
                          View Citations
                        </a>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Related Studies */}
            {relatedStudies.length > 0 && (
              <div className="mt-10">
                <h2 className="text-2xl font-bold mb-6">Related Research</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {relatedStudies.map((relatedStudy: any) => (
                    <Link key={relatedStudy.id} href={`/study/${relatedStudy.id}`}>
                      <Card className="h-full hover:bg-neutral-50 transition-colors cursor-pointer">
                        <CardContent className="p-5">
                          <Badge variant="outline" className="mb-3">
                            {relatedStudy.category}
                          </Badge>
                          <h3 className="font-bold mb-2 line-clamp-2">{relatedStudy.title}</h3>
                          <p className="text-sm text-neutral-600 line-clamp-3">{relatedStudy.abstract}</p>
                        </CardContent>
                      </Card>
                    </Link>
                  ))}
                </div>
              </div>
            )}

            {/* Related Blogs */}
            <div className="mt-12">
              <RelatedBlogs studyId={study.id} />
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default StudyPage;