import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { HiArrowLeft, HiDownload, HiExternalLink, HiUser, HiBookOpen, HiCalendar, HiDocumentText, HiClipboardCheck, HiPhotograph } from "react-icons/hi";
import { Helmet } from "react-helmet";
import { useToast } from "@/hooks/use-toast";
import RelatedBlogs from "@/components/studies/related-blogs";
import JsonLd, { generateMedicalArticleSchema, generateBreadcrumbSchema } from "@/components/seo/JsonLd";

const StudyPage = () => {
  const { id } = useParams();
  const studyId = id ? parseInt(id) : 0; // Provide fallback to prevent NaN
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Define the Study type to match what's returned from the API
  interface Study {
    id: number;
    title: string;
    abstract: string;
    authors: string;
    journal: string;
    publishDate: string;
    category: string;
    methods?: string;
    results?: string;
    conclusion?: string;
    doi?: string;
    pdfUrl?: string;
    citationUrl?: string;
    imageUrl?: string;
    image_url?: string; // Added to handle snake_case from API
    imageAlt?: string;
    image_alt?: string; // Added to handle snake_case from API
    autoGeneratedImage?: boolean;
    auto_generated_image?: boolean; // Added to handle snake_case from API
    year?: number;
    studyType?: string;
    citations?: number;
    fullTextAvailable?: boolean;
  }

  const { data: study, isLoading, error } = useQuery<Study>({
    queryKey: [`/api/studies/${studyId}`],
  });
  
  // Create a fallback image URL for studies with enhanced visual appeal
  const fallbackImageUrl = "/images/fallback-study-image.svg";
  
  // Special case for study #1000 that has known issues
  const study1000ImageUrl = "/images/study-1000-fallback.svg";
  
  // Enhanced helper function to process image URLs correctly and handle all edge cases
  const getProcessedImageUrl = (study?: Study) => {
    if (!study) return fallbackImageUrl;
    
    // Special handling for study #1000
    if (studyId === 1000) {
      return study1000ImageUrl;
    }
    
    // Check for both camelCase and snake_case property names
    const imageUrl = study.imageUrl || study.image_url;
    
    // If no URL provided or it's null/empty, use fallback
    if (!imageUrl || imageUrl.trim() === '') return fallbackImageUrl;
    
    // If it's already a fully qualified URL (starts with http/https), use it directly
    if (imageUrl.startsWith('http')) {
      // Sometimes external URLs might have issues, if it's a placeholder service, use our local fallback
      if (imageUrl.includes('placehold.co')) {
        return fallbackImageUrl;
      }
      return imageUrl;
    }
    
    // If it's a root-relative URL (starts with /), use it as is
    if (imageUrl.startsWith('/')) return imageUrl;
    
    // For any other case, prepend / to make it a root-relative URL
    return `/${imageUrl}`;
  };
  
  // Mutation for generating an AI image for this study
  const generateImageMutation = useMutation({
    mutationFn: () => {
      return fetch(`/api/images/generate/${studyId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
      }).then(res => {
        if (!res.ok) throw new Error('Failed to generate image');
        return res.json();
      });
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: [`/api/studies/${studyId}`] });
      toast({
        title: "Image Generated Successfully",
        description: "A new scientific visualization has been created for this study.",
      });
    },
    onError: (error) => {
      console.error('Image generation error:', error);
      toast({
        title: "Image Generation Failed",
        description: "Unable to generate an image. Please try again later.",
        variant: "destructive",
      });
    }
  });

  // Get all studies for related studies section
  const { data: allStudies } = useQuery<any[]>({
    queryKey: ['/api/studies'],
  });

  // Get related studies (same category, exclude current)
  const relatedStudies = allStudies && study
    ? allStudies
        .filter((s: any) => s.category === study.category && s.id !== studyId)
        .slice(0, 3)
    : [];

  if (isLoading) {
    return (
      <div className="min-h-screen bg-white py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="h-6 bg-neutral-200 rounded w-48 mb-6 animate-pulse"></div>
            <div className="h-10 bg-neutral-200 rounded w-full mb-4 animate-pulse"></div>
            <div className="flex space-x-4 mb-6">
              <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
              <div className="h-6 bg-neutral-200 rounded w-24 animate-pulse"></div>
            </div>
            <div className="space-y-2 mb-8">
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-full animate-pulse"></div>
              <div className="h-4 bg-neutral-200 rounded w-3/4 animate-pulse"></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (error || !study) {
    return (
      <div className="min-h-screen bg-white py-12">
        <div className="container mx-auto px-4 text-center">
          <Card className="max-w-md mx-auto">
            <CardContent className="pt-6 pb-6">
              <h1 className="text-xl font-bold mb-4">Study Not Found</h1>
              <p className="text-neutral-600 mb-6">
                {error instanceof Error 
                  ? error.message 
                  : "We couldn't find the study you're looking for. It may have been removed or the ID is incorrect."}
              </p>
              <Link href="/recent">
                <Button>
                  <HiArrowLeft className="mr-2" />
                  Browse Recent Studies
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <>
      <Helmet>
        <title>{study.title} | Hydrogen Studies Research</title>
        <meta name="description" content={study.abstract?.substring(0, 160) + "..."} />
        <meta name="keywords" content={`hydrogen therapy, molecular hydrogen, ${study.category.toLowerCase()}, research study, scientific evidence, health effects`} />
        <meta name="author" content={study.authors} />
        <meta name="date" content={study.publishDate} />
        <link rel="canonical" href={`https://hydrogenstudies.com/study/${study.id}`} />
        
        {/* Open Graph Tags */}
        <meta property="og:title" content={`${study.title} | Hydrogen Studies`} />
        <meta property="og:description" content={study.abstract?.substring(0, 200) + "..."} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`https://hydrogenstudies.com/study/${study.id}`} />
        <meta property="og:image" content={study.imageUrl || fallbackImageUrl} />
        <meta property="article:published_time" content={study.publishDate} />
        <meta property="article:section" content={study.category} />
        
        {/* Twitter Card Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={study.title} />
        <meta name="twitter:description" content={study.abstract?.substring(0, 200) + "..."} />
        <meta name="twitter:image" content={study.imageUrl || fallbackImageUrl} />
      </Helmet>
      
      {/* Structured Data */}
      <JsonLd 
        type="MedicalScholarlyArticle"
        data={generateMedicalArticleSchema(study)}
      />
      
      {/* Breadcrumb Schema */}
      <JsonLd 
        type="BreadcrumbList"
        data={generateBreadcrumbSchema([
          { name: 'Home', url: 'https://hydrogenstudies.com' },
          { name: 'Research Studies', url: 'https://hydrogenstudies.com/studies' },
          { name: study.category, url: `https://hydrogenstudies.com/category/${encodeURIComponent(study.category)}` },
          { name: study.title, url: `https://hydrogenstudies.com/study/${study.id}` }
        ])}
      />

      <section className="bg-white py-8 md:py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            {/* Breadcrumb */}
            <nav aria-label="Breadcrumb" className="mb-6">
              <ol className="flex items-center text-sm text-neutral-500" itemScope itemType="https://schema.org/BreadcrumbList">
                <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem" className="inline-flex items-center">
                  <Link href="/">
                    <span itemProp="name" className="hover:text-primary cursor-pointer">Home</span>
                  </Link>
                  <meta itemProp="position" content="1" />
                  <span className="mx-2" aria-hidden="true">/</span>
                </li>
                <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem" className="inline-flex items-center">
                  <Link href="/categories">
                    <span itemProp="name" className="hover:text-primary cursor-pointer">Categories</span>
                  </Link>
                  <meta itemProp="position" content="2" />
                  <span className="mx-2" aria-hidden="true">/</span>
                </li>
                <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem" className="inline-flex items-center">
                  <Link href={`/category/${encodeURIComponent(study.category.toLowerCase())}`}>
                    <span itemProp="name" className="hover:text-primary cursor-pointer">{study.category}</span>
                  </Link>
                  <meta itemProp="position" content="3" />
                  <span className="mx-2" aria-hidden="true">/</span>
                </li>
                <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem" className="inline-flex items-center" aria-current="page">
                  <span itemProp="name" className="text-neutral-800">Study</span>
                  <meta itemProp="position" content="4" />
                </li>
              </ol>
            </nav>

            {/* Study Header */}
            <header className="mb-8">
              <div className="flex items-center mb-3">
                <Badge variant="secondary" className="bg-primary/10 text-primary hover:bg-primary/15">
                  {study.category}
                </Badge>
                {study.year && (
                  <time dateTime={study.year.toString()} className="ml-4 text-neutral-500 flex items-center">
                    <HiCalendar className="mr-1" aria-hidden="true" /> {study.year}
                  </time>
                )}
              </div>
              
              <h1 className="text-3xl md:text-4xl font-bold mb-4">{study.title}</h1>
              
              <div className="flex flex-wrap items-center text-neutral-600 gap-y-2">
                <span className="flex items-center mr-6">
                  <HiUser className="mr-1" aria-hidden="true" /> 
                  <span itemProp="author">{study.authors}</span>
                </span>
                <span className="flex items-center mr-6">
                  <HiBookOpen className="mr-1" aria-hidden="true" /> 
                  <span itemProp="publisher">{study.journal}</span>
                </span>
                <span className="flex items-center">
                  <HiDocumentText className="mr-1" aria-hidden="true" /> 
                  <span>{study.citations || "0"} citations</span>
                </span>
              </div>
            </header>

            {/* Study Content */}
            <article className="bg-white border border-neutral-200 rounded-xl shadow-sm mb-10" itemScope itemType="https://schema.org/MedicalScholarlyArticle">
              <div className="p-6 md:p-8">
                <section aria-labelledby="visualization-heading">
                  <h2 id="visualization-heading" className="text-xl font-semibold mb-4">Research Visualization</h2>
                  {/* Study Image */}
                  <figure className="mb-8 rounded-lg overflow-hidden">
                    {/* Image with fallback */}
                    <div className="relative">
                      {/* Direct image element with robust fallback system */}
                      {studyId === 1000 ? (
                        <img 
                          src="https://d18e5e2b-bbfe-4588-9c10-a5e2efc25a8e-00-19md0w0nv1ssf.spock.replit.dev/images/study-1000-fallback.svg"
                          alt={`Scientific visualization for Future Directions in Hydrogen Studies (Study #1000)`}
                          className="w-full h-auto object-cover shadow-sm rounded-md"
                          itemProp="image"
                          onError={(e) => {
                            const target = e.target as HTMLImageElement;
                            target.onerror = null;
                            console.log("Study 1000 fallback image failed, using text placeholder");
                            target.src = `https://placehold.co/800x500/e2f3ff/003366?text=Future+Directions+in+Hydrogen+Studies`;
                          }}
                        />
                      ) : (
                        <img 
                          src={getProcessedImageUrl(study)}
                          alt={study.imageAlt || study.image_alt || `Scientific visualization of hydrogen therapy research: ${study.title}`}
                          className="w-full h-auto object-cover shadow-sm rounded-md" 
                          itemProp="image"
                          onError={(e) => {
                            // Fallback if the image fails to load
                            const target = e.target as HTMLImageElement;
                            target.onerror = null; // Prevent infinite loop
                            console.log("Image load error, using text placeholder");
                            
                            // Use a direct placeholder service that's reliable
                            target.src = `https://placehold.co/800x500/e2f3ff/003366?text=${encodeURIComponent(study?.title || 'Hydrogen Research Study')}`;
                            
                            // Update alt text for accessibility
                            target.alt = `Scientific visualization of hydrogen therapy research: ${study?.title}`;
                          }}
                        />
                      )}
                      
                      {/* Generate Image Button - Only show if image is missing or using fallback */}
                      {(!(study.imageUrl || study.image_url) || (study.imageUrl === fallbackImageUrl || study.image_url === fallbackImageUrl)) && (
                        <div className="absolute bottom-0 left-0 right-0 bg-neutral-800/70 p-3 flex justify-center">
                          <Button 
                            variant="secondary"
                            className="flex items-center gap-2 bg-white hover:bg-neutral-100"
                            onClick={() => generateImageMutation.mutate()}
                            disabled={generateImageMutation.isPending}
                          >
                            <HiPhotograph className="w-4 h-4" />
                            {generateImageMutation.isPending ? 'Generating...' : 'Generate Scientific Visual'}
                          </Button>
                        </div>
                      )}
                    </div>
                    
                    <figcaption className="flex justify-between items-start mt-2">
                      <p className="text-xs text-neutral-500 italic">
                        {(study.autoGeneratedImage || study.auto_generated_image) ? 
                          "AI-generated visualization of the study's hydrogen mechanisms and effects" : 
                          "Visual representation of hydrogen effects related to this research"}
                      </p>
                      
                      {/* Image attribution if available */}
                      {(study.imageAlt || study.image_alt) && (
                        <span className="text-xs text-neutral-400">
                          {study.imageAlt || study.image_alt}
                        </span>
                      )}
                    </figcaption>
                  </figure>
                </section>

                <section aria-labelledby="abstract-heading">
                  <h2 id="abstract-heading" className="text-xl font-semibold mb-4">Abstract</h2>
                  <div className="prose max-w-none prose-neutral mb-8">
                    <p className="text-lg leading-relaxed" itemProp="abstract">{study.abstract}</p>
                  </div>
                </section>

                {/* Methods Section */}
                {study.methods && (
                  <section aria-labelledby="methods-heading">
                    <Separator className="my-6" />
                    <h2 id="methods-heading" className="text-xl font-semibold mb-4">Methods</h2>
                    <div className="prose max-w-none prose-neutral mb-6" itemProp="methodDescription">
                      <p>{study.methods}</p>
                    </div>
                  </section>
                )}

                {/* Results Section */}
                {study.results && (
                  <section aria-labelledby="results-heading">
                    <Separator className="my-6" />
                    <h2 id="results-heading" className="text-xl font-semibold mb-4">Results</h2>
                    <div className="prose max-w-none prose-neutral mb-6" itemProp="resultDescription">
                      <p>{study.results}</p>
                    </div>
                  </section>
                )}

                {/* Conclusion Section */}
                {study.conclusion && (
                  <section aria-labelledby="conclusion-heading">
                    <Separator className="my-6" />
                    <h2 id="conclusion-heading" className="text-xl font-semibold mb-4">Conclusion</h2>
                    <div className="prose max-w-none prose-neutral mb-6" itemProp="conclusion">
                      <p>{study.conclusion}</p>
                    </div>
                  </section>
                )}

                {/* Study Metadata */}
                <Separator className="my-6" />
                <section aria-labelledby="metadata-heading" className="mt-6">
                  <h2 id="metadata-heading" className="sr-only">Study Metadata</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {study.doi && (
                      <div>
                        <p className="text-sm font-medium text-neutral-500 mb-1">DOI Reference</p>
                        <p className="text-sm">
                          <a 
                            href={`https://doi.org/${study.doi}`} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="text-primary hover:underline flex items-center"
                            itemProp="identifier"
                          >
                            {study.doi} <HiExternalLink className="ml-1" />
                          </a>
                        </p>
                      </div>
                    )}
                    
                    {study.pdfUrl && (
                      <div>
                        <p className="text-sm font-medium text-neutral-500 mb-1">Full Text Access</p>
                        <Button 
                          variant="outline" 
                          size="sm"
                          className="flex items-center text-sm"
                          asChild
                        >
                          <a href={study.pdfUrl} target="_blank" rel="noopener noreferrer">
                            <HiDownload className="mr-1" /> Download PDF
                          </a>
                        </Button>
                      </div>
                    )}
                    
                    {study.citationUrl && (
                      <div>
                        <p className="text-sm font-medium text-neutral-500 mb-1">Citation Information</p>
                        <Button 
                          variant="outline" 
                          size="sm"
                          className="flex items-center text-sm"
                          asChild
                        >
                          <a href={study.citationUrl} target="_blank" rel="noopener noreferrer">
                            <HiClipboardCheck className="mr-1" /> Copy Citation
                          </a>
                        </Button>
                      </div>
                    )}
                  </div>
                </section>
              </div>
            </article>

            {/* Related Studies Section */}
            {relatedStudies.length > 0 && (
              <section aria-labelledby="related-studies-heading" className="mt-12">
                <h2 id="related-studies-heading" className="text-2xl font-bold mb-6">Related Studies</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {relatedStudies.map((relatedStudy: any) => (
                    <Link key={relatedStudy.id} href={`/study/${relatedStudy.id}`}>
                      <Card className="h-full hover:shadow-md transition-shadow">
                        <CardContent className="p-5">
                          <Badge variant="outline" className="mb-3">
                            {relatedStudy.category}
                          </Badge>
                          <h3 className="font-bold mb-2 line-clamp-2">{relatedStudy.title}</h3>
                          <p className="text-sm text-neutral-600 line-clamp-3">{relatedStudy.abstract}</p>
                        </CardContent>
                      </Card>
                    </Link>
                  ))}
                </div>
              </section>
            )}

            {/* Related Blogs */}
            <section aria-labelledby="related-blogs-heading" className="mt-12">
              <h2 id="related-blogs-heading" className="sr-only">Related Blog Articles</h2>
              <RelatedBlogs studyId={study.id} />
            </section>
          </div>
        </div>
      </section>
    </>
  );
};

export default StudyPage;