/**
 * Admin Link Management Routes
 * CRUD endpoints for managing smart internal links
 */
import { Router, Request, Response } from "express";
import { requireAdmin } from "../auth";
import { db } from "../db";
import { smartLinks, studies, blogArticles } from "../../shared/schema";
import { eq, and, sql, desc, count } from "drizzle-orm";

const router = Router();

/**
 * GET /api/admin/links
 * List smart links with pagination and filtering.
 * Query params: page, limit, type (fromType filter), active (true/false)
 */
router.get("/", requireAdmin, async (req: Request, res: Response) => {
  try {
    const page = Math.max(1, parseInt(req.query.page as string) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit as string) || 50));
    const offset = (page - 1) * limit;
    const typeFilter = req.query.type as string | undefined;
    const activeFilter = req.query.active as string | undefined;

    // Build WHERE conditions
    const conditions = [];
    if (typeFilter) {
      conditions.push(eq(smartLinks.fromType, typeFilter));
    }
    if (activeFilter !== undefined) {
      conditions.push(eq(smartLinks.isActive, activeFilter === "true"));
    }

    const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

    // Get total count
    const [totalResult] = await db
      .select({ value: count() })
      .from(smartLinks)
      .where(whereClause);
    const total = Number(totalResult?.value || 0);

    // Get paginated links
    const links = whereClause
      ? await db
          .select()
          .from(smartLinks)
          .where(whereClause)
          .orderBy(desc(smartLinks.createdAt))
          .limit(limit)
          .offset(offset)
      : await db
          .select()
          .from(smartLinks)
          .orderBy(desc(smartLinks.createdAt))
          .limit(limit)
          .offset(offset);

    // Collect unique IDs to fetch titles
    const studyIds = new Set<number>();
    const blogIds = new Set<number>();

    for (const link of links) {
      if (link.fromType === "study") studyIds.add(link.fromId);
      if (link.fromType === "blog") blogIds.add(link.fromId);
      if (link.toType === "study") studyIds.add(link.toId);
      if (link.toType === "blog") blogIds.add(link.toId);
    }

    // Fetch study titles
    const studyTitles: Record<number, string> = {};
    if (studyIds.size > 0) {
      const studyRows = await db
        .select({ id: studies.id, title: studies.title, plainLanguageTitle: studies.plainLanguageTitle })
        .from(studies)
        .where(sql`${studies.id} IN (${sql.join(Array.from(studyIds).map(id => sql`${id}`), sql`, `)})`);
      for (const s of studyRows) {
        studyTitles[s.id] = s.plainLanguageTitle || s.title;
      }
    }

    // Fetch blog titles
    const blogTitles: Record<number, string> = {};
    if (blogIds.size > 0) {
      const blogRows = await db
        .select({ id: blogArticles.id, title: blogArticles.title })
        .from(blogArticles)
        .where(sql`${blogArticles.id} IN (${sql.join(Array.from(blogIds).map(id => sql`${id}`), sql`, `)})`);
      for (const b of blogRows) {
        blogTitles[b.id] = b.title;
      }
    }

    // Enrich links with titles
    const enrichedLinks = links.map((link) => ({
      ...link,
      fromTitle:
        link.fromType === "study"
          ? studyTitles[link.fromId] || `Study #${link.fromId}`
          : link.fromType === "blog"
            ? blogTitles[link.fromId] || `Blog #${link.fromId}`
            : `${link.fromType} #${link.fromId}`,
      toTitle:
        link.toType === "study"
          ? studyTitles[link.toId] || `Study #${link.toId}`
          : link.toType === "blog"
            ? blogTitles[link.toId] || `Blog #${link.toId}`
            : `${link.toType} #${link.toId}`,
    }));

    res.json({ data: enrichedLinks, total, page, limit });
  } catch (error) {
    console.error("Failed to fetch links:", error);
    res.status(500).json({ error: "Failed to fetch links" });
  }
});

/**
 * GET /api/admin/links/stats
 * Return aggregate link statistics
 */
router.get("/stats", requireAdmin, async (_req: Request, res: Response) => {
  try {
    const result = await db.execute(sql`
      SELECT
        count(*)::int AS "totalLinks",
        count(*) FILTER (WHERE is_active = true)::int AS "activeLinks",
        count(*) FILTER (WHERE auto_generated = true)::int AS "autoGenerated",
        count(*) FILTER (WHERE auto_generated = false)::int AS "manual",
        jsonb_build_object(
          'study_to_study', count(*) FILTER (WHERE from_type = 'study' AND to_type = 'study'),
          'study_to_blog', count(*) FILTER (WHERE from_type = 'study' AND to_type = 'blog'),
          'blog_to_study', count(*) FILTER (WHERE from_type = 'blog' AND to_type = 'study'),
          'blog_to_blog', count(*) FILTER (WHERE from_type = 'blog' AND to_type = 'blog')
        ) AS "byType"
      FROM smart_links
    `);

    const row: any = result.rows?.[0] || (result as any)[0] || {};
    res.json({
      totalLinks: Number(row.totalLinks) || 0,
      activeLinks: Number(row.activeLinks) || 0,
      autoGenerated: Number(row.autoGenerated) || 0,
      manual: Number(row.manual) || 0,
      byType: typeof row.byType === "string" ? JSON.parse(row.byType) : row.byType || {},
    });
  } catch (error) {
    console.error("Failed to fetch link stats:", error);
    res.status(500).json({ error: "Failed to fetch link stats" });
  }
});

/**
 * POST /api/admin/links
 * Create a manual link
 */
router.post("/", requireAdmin, async (req: Request, res: Response) => {
  try {
    const { fromType, fromId, toType, toId, anchorText, context, linkType } = req.body;

    if (!fromType || !fromId || !toType || !toId || !anchorText) {
      return res.status(400).json({ error: "Missing required fields: fromType, fromId, toType, toId, anchorText" });
    }

    const [newLink] = await db
      .insert(smartLinks)
      .values({
        fromType,
        fromId: Number(fromId),
        toType,
        toId: Number(toId),
        anchorText,
        context: context || null,
        linkType: linkType || "contextual",
        autoGenerated: false,
        isActive: true,
      })
      .returning();

    res.status(201).json(newLink);
  } catch (error) {
    console.error("Failed to create link:", error);
    res.status(500).json({ error: "Failed to create link" });
  }
});

/**
 * PUT /api/admin/links/:id
 * Update a link (anchorText, relevanceScore, isActive, linkType)
 */
router.put("/:id", requireAdmin, async (req: Request, res: Response) => {
  try {
    const linkId = parseInt(req.params.id);
    if (isNaN(linkId)) {
      return res.status(400).json({ error: "Invalid link ID" });
    }

    const { anchorText, relevanceScore, isActive, linkType } = req.body;

    const updates: Record<string, any> = {};
    if (anchorText !== undefined) updates.anchorText = anchorText;
    if (relevanceScore !== undefined) updates.relevanceScore = Number(relevanceScore);
    if (isActive !== undefined) updates.isActive = Boolean(isActive);
    if (linkType !== undefined) updates.linkType = linkType;

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({ error: "No valid update fields provided" });
    }

    const [updated] = await db
      .update(smartLinks)
      .set(updates)
      .where(eq(smartLinks.id, linkId))
      .returning();

    if (!updated) {
      return res.status(404).json({ error: "Link not found" });
    }

    res.json(updated);
  } catch (error) {
    console.error("Failed to update link:", error);
    res.status(500).json({ error: "Failed to update link" });
  }
});

/**
 * DELETE /api/admin/links/:id
 * Soft delete — sets isActive=false rather than removing the row
 */
router.delete("/:id", requireAdmin, async (req: Request, res: Response) => {
  try {
    const linkId = parseInt(req.params.id);
    if (isNaN(linkId)) {
      return res.status(400).json({ error: "Invalid link ID" });
    }

    const [updated] = await db
      .update(smartLinks)
      .set({ isActive: false })
      .where(eq(smartLinks.id, linkId))
      .returning();

    if (!updated) {
      return res.status(404).json({ error: "Link not found" });
    }

    res.json({ success: true, link: updated });
  } catch (error) {
    console.error("Failed to delete link:", error);
    res.status(500).json({ error: "Failed to delete link" });
  }
});

/**
 * POST /api/admin/links/rebuild
 * Trigger the internal linking engine to rebuild all links
 */
router.post("/rebuild", requireAdmin, async (_req: Request, res: Response) => {
  try {
    const { buildAllStudyLinks, buildAllBlogLinks } = await import(
      "../services/internal-linking-engine"
    );

    const studyResult = await buildAllStudyLinks();
    const blogResult = await buildAllBlogLinks();

    res.json({
      success: true,
      studyLinks: studyResult,
      blogLinks: blogResult,
      totalProcessed: studyResult.processed + blogResult.processed,
      totalLinksCreated: studyResult.linksCreated + blogResult.linksCreated,
    });
  } catch (error) {
    console.error("Failed to rebuild links:", error);
    res.status(500).json({ error: "Failed to rebuild links" });
  }
});

export default router;
