import { Router } from "express";
import {
  generateImageForStudy,
  findStudiesNeedingImages,
  batchGenerateImagesForStudies,
} from "../image-generator";
import { db } from "../db";
import { studies as studiesTable } from "../../shared/schema";
import { isNull, or, eq } from "drizzle-orm";

const router = Router();

/**
 * Generate image for a specific study
 */
router.post("/generate/:studyId", async (req, res) => {
  try {
    const studyId = parseInt(req.params.studyId);
    if (isNaN(studyId)) {
      return res
        .status(400)
        .json({ success: false, message: "Invalid study ID" });
    }

    // Get the study to check if it exists
    const study = await db
      ?.select()
      .from(studiesTable)
      .where(eq(studiesTable.id, studyId))
      .limit(1);
    if (!study || study.length === 0) {
      return res.status(404).json({
        success: false,
        message: `Study with ID ${studyId} not found`,
      });
    }

    // Check if OpenAI API key is available
    if (!process.env.OPENAI_API_KEY) {
      console.log(
        `No OpenAI API key available. Using placeholder image for study ${studyId}`,
      );

      // Create a placeholder image URL with study title
      const titleForPlaceholder = encodeURIComponent(
        study[0].title.substring(0, 30),
      );
      const placeholderUrl = `https://placehold.co/800x600/e2f3ff/003366?text=${titleForPlaceholder}`;

      // Update the study with the placeholder URL
      await db
        ?.update(studiesTable)
        .set({
          imageUrl: placeholderUrl,
          imageAlt: `Scientific visualization: ${study[0].title}`,
          autoGeneratedImage: true,
        })
        .where(eq(studiesTable.id, studyId));

      return res.json({
        success: true,
        message: "Added placeholder image (OpenAI API key not available)",
        imageUrl: placeholderUrl,
      });
    }

    console.log(`Generating image for study ${studyId}...`);
    const result = await generateImageForStudy(studyId);
    console.log(`Image generation result:`, result);
    return res.json(result);
  } catch (error) {
    console.error("Error generating image for study:", error);

    // If there's an error, still try to update with a placeholder
    try {
      const studyId = parseInt(req.params.studyId);
      const study = await db
        ?.select({
          id: studiesTable.id,
          title: studiesTable.title,
        })
        .from(studiesTable)
        .where(eq(studiesTable.id, studyId))
        .limit(1);

      if (study && study.length > 0) {
        const titleForPlaceholder = encodeURIComponent(
          study[0].title.substring(0, 30),
        );
        const placeholderUrl = `https://placehold.co/800x600/e2f3ff/003366?text=${titleForPlaceholder}`;

        // Update study with placeholder
        await db
          ?.update(studiesTable)
          .set({
            imageUrl: placeholderUrl,
            imageAlt: `Study visualization: ${study[0].title}`,
            autoGeneratedImage: true,
          })
          .where(eq(studiesTable.id, studyId));

        return res.json({
          success: true,
          message: "Added placeholder image (image generation failed)",
          imageUrl: placeholderUrl,
        });
      }
    } catch (fallbackError) {
      console.error("Error creating fallback placeholder:", fallbackError);
    }

    return res.status(500).json({
      success: false,
      message: `Error generating image: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

/**
 * Find studies that need images
 */
router.get("/find-studies-needing-images", async (req, res) => {
  try {
    const limit = req.query.limit ? parseInt(req.query.limit as string) : 20;
    const studyIds = await findStudiesNeedingImages(limit);
    return res.json({
      success: true,
      studyIds,
      count: studyIds.length,
    });
  } catch (error) {
    console.error("Error finding studies needing images:", error);
    return res.status(500).json({
      success: false,
      message: `Error finding studies: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

/**
 * Batch generate images for multiple studies
 */
router.post("/batch-generate", async (req, res) => {
  try {
    const { studyIds, limit } = req.body;

    // If studyIds provided, use them, otherwise auto-find studies that need images
    const idsToProcess =
      studyIds || (await findStudiesNeedingImages(limit || 10));

    if (!idsToProcess || idsToProcess.length === 0) {
      return res.json({
        success: false,
        message: "No studies to process",
      });
    }

    // Start the batch process with the array of study IDs
    setTimeout(() => {
      batchGenerateImagesForStudies(idsToProcess);
    }, 100);

    // Log that the batch process has started
    console.log(
      `Started batch image generation for ${idsToProcess.length} studies`,
    );

    // Return immediately to let the process run in background
    return res.json({
      success: true,
      message: `Started batch image generation for ${idsToProcess.length} studies`,
      studyIds: idsToProcess,
    });
  } catch (error) {
    console.error("Error starting batch image generation:", error);
    return res.status(500).json({
      success: false,
      message: `Error starting batch process: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

/**
 * Auto-generate images for all studies that don't have images
 * This will process studies in batches to avoid overwhelming the system
 */
router.post("/auto-generate-all", async (req, res) => {
  try {
    // Query database for all studies without images
    const studiesWithoutImages = await db
      ?.select({ id: studiesTable.id })
      .from(studiesTable)
      .where(or(isNull(studiesTable.imageUrl), eq(studiesTable.imageUrl, "")));

    const count = studiesWithoutImages?.length || 0;

    if (count === 0) {
      return res.json({
        success: true,
        message: "All studies already have images",
      });
    }

    // Start a background process to generate images for all studies
    // This will run in batches of 10 with a delay between each batch
    const batchSize = Math.min(10, count);
    console.log(
      `Starting auto image generation for ${count} studies in batches of ${batchSize}`,
    );

    // Get the list of study IDs that need images
    const studyIds = studiesWithoutImages?.map((study) => study.id) || [];

    if (studyIds.length > 0) {
      // Process the first batch
      console.log(
        `Starting batch image generation for studies: ${studyIds.slice(0, batchSize).join(", ")}`,
      );

      // Start the batch process in the background
      setTimeout(async () => {
        try {
          // Process studies in batches
          for (let i = 0; i < studyIds.length; i += batchSize) {
            const batch = studyIds.slice(i, i + batchSize);
            console.log(
              `Processing batch ${Math.floor(i / batchSize) + 1} of ${Math.ceil(studyIds.length / batchSize)}`,
            );

            // Generate images for studies in this batch
            for (const studyId of batch) {
              try {
                console.log(`Generating image for study ${studyId}`);
                const result = await generateImageForStudy(studyId);

                if (result.success) {
                  console.log(
                    `Successfully generated image for study ${studyId}`,
                  );
                  // Update the autoGeneratedImage flag
                  await db
                    ?.update(studiesTable)
                    .set({ autoGeneratedImage: true })
                    .where(eq(studiesTable.id, studyId));
                } else {
                  console.error(
                    `Failed to generate image for study ${studyId}: ${result.message}`,
                  );
                }

                // Add a delay between each study to avoid rate limits
                await new Promise((resolve) => setTimeout(resolve, 5000));
              } catch (err) {
                console.error(`Error processing study ${studyId}:`, err);
              }
            }

            // Add a longer delay between batches
            if (i + batchSize < studyIds.length) {
              console.log("Waiting 30 seconds before processing next batch...");
              await new Promise((resolve) => setTimeout(resolve, 30000));
            }
          }

          console.log("Finished auto image generation for all studies");
        } catch (err) {
          console.error("Error in background image generation process:", err);
        }
      }, 100); // Start after a short delay

      // Return immediately without waiting for the process to finish
      return res.json({
        success: true,
        message: `Starting auto image generation for ${count} studies in batches of ${batchSize}. This process will run in the background.`,
        studyIds: studyIds.slice(0, 10), // Return just the first 10 for information
      });
    } else {
      return res.json({
        success: false,
        message: "No studies found that need images",
      });
    }
  } catch (error) {
    console.error("Error starting auto image generation:", error);
    return res.status(500).json({
      success: false,
      message: `Error starting auto image generation: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

export const imageGenerationRoutes = router;
