/**
 * Batch Image Fix
 * 
 * This script ensures all studies in the database have proper image URLs
 * by adding placeholder images where images are missing or invalid.
 */

import { db } from "./db";
import { studies } from "@shared/schema";
import { isNull, sql, eq } from "drizzle-orm";

interface StudyImage {
  id: number;
  title: string;
  imageUrl: string | null;
}

/**
 * Fix missing images for all studies in the database
 */
export async function fixAllStudyImages() {
  try {
    // Find studies with missing images
    const studiesWithoutImages = await db
      .select({
        id: studies.id,
        title: studies.title,
        imageUrl: studies.imageUrl
      })
      .from(studies)
      .where(isNull(studies.imageUrl));

    console.log(`Found ${studiesWithoutImages.length} studies without images`);
    
    // Batch size for processing
    const batchSize = 50;
    let processedCount = 0;
    let successCount = 0;
    
    // Process studies in batches
    for (let i = 0; i < studiesWithoutImages.length; i += batchSize) {
      const batch = studiesWithoutImages.slice(i, i + batchSize);
      
      // Update each study with a placeholder image
      for (const study of batch) {
        await db.update(studies)
          .set({
            imageUrl: `https://placehold.co/800x500/e2f3ff/003366?text=Hydrogen+Study+${study.id}`,
            imageAlt: `Scientific visualization of hydrogen therapy research: ${study.title}`,
            autoGeneratedImage: true
          })
          .where(eq(studies.id, study.id));
        
        processedCount++;
        successCount++;
      }
      
      console.log(`Processed ${processedCount} of ${studiesWithoutImages.length} studies`);
    }
    
    return {
      success: true,
      message: `Successfully added placeholder images to ${successCount} studies`,
      total: studiesWithoutImages.length,
      processed: processedCount,
      fixed: successCount
    };
  } catch (error) {
    console.error("Error fixing study images:", error);
    return {
      success: false,
      message: "Failed to fix study images",
      error: error.message
    };
  }
}

/**
 * Check the image status across all studies
 */
export async function checkImageStatus() {
  try {
    const totalStudies = await db
      .select({ count: sql<number>`count(*)` })
      .from(studies);
    
    const studiesWithImages = await db
      .select({ count: sql<number>`count(*)` })
      .from(studies)
      .where(sql`"imageUrl" is not null`);
    
    const studiesWithPlaceholders = await db
      .select({ count: sql<number>`count(*)` })
      .from(studies)
      .where(sql`"imageUrl" like ${"https://placehold.co%"}`);
    
    const studiesWithCustomImages = Number(studiesWithImages[0].count) - Number(studiesWithPlaceholders[0].count);
    
    return {
      success: true,
      totalStudies: Number(totalStudies[0].count),
      studiesWithImages: Number(studiesWithImages[0].count),
      studiesWithoutImages: Number(totalStudies[0].count) - Number(studiesWithImages[0].count),
      studiesWithPlaceholders: Number(studiesWithPlaceholders[0].count),
      studiesWithCustomImages: studiesWithCustomImages,
      percentageWithImages: Math.round((Number(studiesWithImages[0].count) / Number(totalStudies[0].count)) * 100)
    };
  } catch (error) {
    console.error("Error checking image status:", error);
    return {
      success: false,
      message: "Failed to check image status",
      error: error.message
    };
  }
}