/**
 * Persistent Image Generator
 * Automatically resumes image generation after app restarts until all studies completed
 */

import { generateStudyImage } from './enhanced-image-generator';
import { db } from './db';
import { studies } from '../shared/schema';
import { isNull, or, eq } from 'drizzle-orm';

interface ImageGenerationState {
  isRunning: boolean;
  lastProcessedId: number;
  totalProcessed: number;
  startTime: Date;
  lastRunTime: Date;
}

let generationState: ImageGenerationState = {
  isRunning: false,
  lastProcessedId: 0,
  totalProcessed: 0,
  startTime: new Date(),
  lastRunTime: new Date()
};

/**
 * Initialize persistent image generation on app startup
 */
export async function initializePersistentImageGeneration(): Promise<void> {
  try {
    console.log('Initializing persistent image generation system...');
    
    // Check if there are studies that need enhanced images
    const studiesNeedingImages = await getStudiesNeedingImages();
    
    if (studiesNeedingImages.length === 0) {
      console.log('All studies have enhanced images - no generation needed');
      return;
    }
    
    console.log(`Found ${studiesNeedingImages.length} studies needing enhanced images`);
    
    // Start image generation in background after app startup
    setTimeout(() => {
      startPersistentImageGeneration();
    }, 30000); // Wait 30 seconds after startup
    
  } catch (error) {
    console.error('Error initializing persistent image generation:', error);
  }
}

/**
 * Get studies that need enhanced image generation
 */
async function getStudiesNeedingImages(): Promise<any[]> {
  // Get studies without proper enhanced descriptions or images
  const studiesNeedingEnhancement = await db.select()
    .from(studies)
    .where(or(
      isNull(studies.imageUrl),
      isNull(studies.imageAlt),
      eq(studies.autoGeneratedImage, false)
    ))
    .limit(1000); // Process in chunks
    
  return studiesNeedingEnhancement;
}

/**
 * Start persistent image generation process
 */
async function startPersistentImageGeneration(): Promise<void> {
  if (generationState.isRunning) {
    console.log('Image generation already running');
    return;
  }
  
  generationState.isRunning = true;
  generationState.startTime = new Date();
  
  console.log('Starting persistent image generation...');
  
  try {
    await processImageGeneration();
  } catch (error) {
    console.error('Error in persistent image generation:', error);
    generationState.isRunning = false;
    
    // Retry in 5 minutes on error
    setTimeout(() => {
      console.log('Retrying image generation after error...');
      startPersistentImageGeneration();
    }, 300000);
  }
}

/**
 * Main image generation processing loop
 */
async function processImageGeneration(): Promise<void> {
  while (generationState.isRunning) {
    try {
      // Get next batch of studies needing images
      const studiesNeedingImages = await getStudiesNeedingImages();
      
      if (studiesNeedingImages.length === 0) {
        console.log('✅ All studies have enhanced images - generation complete!');
        generationState.isRunning = false;
        break;
      }
      
      // Process 7 studies (rate limit: 7 images per minute)
      const batch = studiesNeedingImages.slice(0, 7);
      console.log(`Processing batch: studies ${batch.map(s => s.id).join(', ')}`);
      
      // Generate images for batch
      const batchPromises = batch.map(study => 
        generateEnhancedStudyImage(study.id)
      );
      
      const results = await Promise.all(batchPromises);
      
      // Count successful generations
      const successful = results.filter(r => r.success).length;
      generationState.totalProcessed += batch.length;
      generationState.lastRunTime = new Date();
      
      console.log(`Batch complete: ${successful}/${batch.length} successful. Total processed: ${generationState.totalProcessed}`);
      
      // Wait 60 seconds for rate limit (7 images per minute)
      console.log('Waiting 60 seconds for rate limit...');
      await new Promise(resolve => setTimeout(resolve, 60000));
      
    } catch (error) {
      console.error('Error in image generation batch:', error);
      // Continue with next batch after short delay
      await new Promise(resolve => setTimeout(resolve, 10000));
    }
  }
}

/**
 * Generate enhanced image for a single study
 */
async function generateEnhancedStudyImage(studyId: number): Promise<{ success: boolean; studyId: number; error?: string }> {
  try {
    const result = await generateStudyImage(studyId);
    
    if (result.success) {
      console.log(`✓ Study ${studyId}: Enhanced image generated`);
      return { success: true, studyId };
    } else {
      console.log(`✗ Study ${studyId}: ${result.error}`);
      return { success: false, studyId, error: result.error };
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.log(`✗ Study ${studyId}: ${errorMessage}`);
    return { success: false, studyId, error: errorMessage };
  }
}

/**
 * Get current generation status
 */
export function getImageGenerationStatus(): {
  isRunning: boolean;
  totalProcessed: number;
  startTime: Date;
  lastRunTime: Date;
  uptime: string;
} {
  const now = new Date();
  const uptimeMs = now.getTime() - generationState.startTime.getTime();
  const uptimeMinutes = Math.floor(uptimeMs / 60000);
  
  return {
    isRunning: generationState.isRunning,
    totalProcessed: generationState.totalProcessed,
    startTime: generationState.startTime,
    lastRunTime: generationState.lastRunTime,
    uptime: `${uptimeMinutes} minutes`
  };
}

/**
 * Stop image generation process
 */
export function stopImageGeneration(): { stopped: boolean; message: string } {
  if (!generationState.isRunning) {
    return { stopped: false, message: 'Image generation is not running' };
  }
  
  generationState.isRunning = false;
  return { stopped: true, message: 'Image generation stopped successfully' };
}

/**
 * Manually trigger image generation
 */
export async function triggerImageGeneration(): Promise<{ started: boolean; message: string }> {
  if (generationState.isRunning) {
    return { started: false, message: 'Image generation is already running' };
  }
  
  // Start generation immediately
  startPersistentImageGeneration();
  
  return { started: true, message: 'Image generation started successfully' };
}