/**
 * Link Management Page
 * Admin interface for managing smart internal links for SEO
 */
import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import AdminLayout from "@/components/admin/AdminLayout";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Link2,
  Plus,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  Check,
  X,
  Pencil,
  Trash2,
  Loader2,
  ExternalLink,
} from "lucide-react";

interface SmartLink {
  id: number;
  fromType: string;
  fromId: number;
  toType: string;
  toId: number;
  anchorText: string;
  context: string | null;
  relevanceScore: number | null;
  linkType: string | null;
  autoGenerated: boolean | null;
  isActive: boolean | null;
  createdAt: string;
  fromTitle: string;
  toTitle: string;
}

interface LinkStats {
  totalLinks: number;
  activeLinks: number;
  autoGenerated: number;
  manual: number;
  byType: Record<string, number>;
}

interface LinksResponse {
  data: SmartLink[];
  total: number;
  page: number;
  limit: number;
}

const LINK_TYPE_OPTIONS = [
  { value: "contextual", label: "Contextual" },
  { value: "related", label: "Related" },
  { value: "citation", label: "Citation" },
  { value: "update", label: "Update" },
];

const CONTENT_TYPE_OPTIONS = [
  { value: "study", label: "Study" },
  { value: "blog", label: "Blog" },
];

function linkTypeBadgeVariant(linkType: string | null): string {
  switch (linkType) {
    case "citation":
      return "bg-primary/10 text-primary";
    case "related":
      return "bg-green-100 text-green-800";
    case "contextual":
      return "bg-purple-100 text-purple-800";
    case "update":
      return "bg-amber-100 text-amber-800";
    default:
      return "bg-muted text-foreground";
  }
}

export default function LinkManagementPage() {
  const { toast } = useToast();

  // Filters and pagination
  const [page, setPage] = useState(1);
  const [limit] = useState(50);
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [activeFilter, setActiveFilter] = useState<string>("all");

  // Dialogs
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [editingLinkId, setEditingLinkId] = useState<number | null>(null);
  const [editAnchorText, setEditAnchorText] = useState("");

  // Create form
  const [newLink, setNewLink] = useState({
    fromType: "study",
    fromId: "",
    toType: "blog",
    toId: "",
    anchorText: "",
    context: "",
    linkType: "contextual",
  });

  // Build query string for links endpoint
  const queryParams = new URLSearchParams();
  queryParams.set("page", String(page));
  queryParams.set("limit", String(limit));
  if (typeFilter !== "all") queryParams.set("type", typeFilter);
  if (activeFilter !== "all") queryParams.set("active", activeFilter);

  // Fetch links
  const {
    data: linksData,
    isLoading: linksLoading,
    refetch: refetchLinks,
  } = useQuery<LinksResponse>({
    queryKey: [`/api/admin/links?${queryParams.toString()}`],
    staleTime: 30 * 1000,
  });

  // Fetch stats
  const { data: stats, isLoading: statsLoading } = useQuery<LinkStats>({
    queryKey: ["/api/admin/links/stats"],
    staleTime: 60 * 1000,
  });

  // Create link mutation
  const createMutation = useMutation({
    mutationFn: (data: typeof newLink) =>
      apiRequest("POST", "/api/admin/links", {
        ...data,
        fromId: Number(data.fromId),
        toId: Number(data.toId),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links/stats"] });
      toast({ title: "Link created", description: "New internal link has been created." });
      setShowCreateDialog(false);
      setNewLink({
        fromType: "study",
        fromId: "",
        toType: "blog",
        toId: "",
        anchorText: "",
        context: "",
        linkType: "contextual",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Failed to create link",
        description: error.message || "An error occurred",
        variant: "destructive",
      });
    },
  });

  // Update link mutation
  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: Record<string, any> }) =>
      apiRequest("PUT", `/api/admin/links/${id}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links/stats"] });
      toast({ title: "Link updated" });
      setEditingLinkId(null);
    },
    onError: (error: any) => {
      toast({
        title: "Failed to update link",
        description: error.message || "An error occurred",
        variant: "destructive",
      });
    },
  });

  // Delete (soft) mutation
  const deleteMutation = useMutation({
    mutationFn: (id: number) => apiRequest("DELETE", `/api/admin/links/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links/stats"] });
      toast({ title: "Link deactivated" });
    },
    onError: (error: any) => {
      toast({
        title: "Failed to delete link",
        description: error.message || "An error occurred",
        variant: "destructive",
      });
    },
  });

  // Rebuild all links mutation
  const rebuildMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/admin/links/rebuild"),
    onSuccess: async (res) => {
      const result = await res.json();
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/links/stats"] });
      toast({
        title: "Links rebuilt",
        description: `Processed ${result.totalProcessed} items, created ${result.totalLinksCreated} new links.`,
      });
    },
    onError: (error: any) => {
      toast({
        title: "Rebuild failed",
        description: error.message || "An error occurred",
        variant: "destructive",
      });
    },
  });

  const links = linksData?.data || [];
  const totalLinks = linksData?.total || 0;
  const totalPages = Math.ceil(totalLinks / limit);

  const handleToggleActive = (link: SmartLink) => {
    updateMutation.mutate({
      id: link.id,
      data: { isActive: !link.isActive },
    });
  };

  const handleSaveAnchorText = (linkId: number) => {
    if (!editAnchorText.trim()) return;
    updateMutation.mutate({
      id: linkId,
      data: { anchorText: editAnchorText.trim() },
    });
  };

  const startEditAnchor = (link: SmartLink) => {
    setEditingLinkId(link.id);
    setEditAnchorText(link.anchorText);
  };

  const cancelEditAnchor = () => {
    setEditingLinkId(null);
    setEditAnchorText("");
  };

  return (
    <AdminLayout title="Link Management" description="Manage smart internal links for SEO">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {statsLoading ? (
          <>
            {[1, 2, 3, 4].map((i) => (
              <Card key={i}>
                <CardContent className="p-4">
                  <Skeleton className="h-4 w-20 mb-2" />
                  <Skeleton className="h-8 w-16" />
                </CardContent>
              </Card>
            ))}
          </>
        ) : (
          <>
            <Card>
              <CardContent className="p-4">
                <p className="text-sm text-muted-foreground">Total Links</p>
                <p className="text-2xl font-bold">{stats?.totalLinks || 0}</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4">
                <p className="text-sm text-muted-foreground">Active</p>
                <p className="text-2xl font-bold text-green-600">{stats?.activeLinks || 0}</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4">
                <p className="text-sm text-muted-foreground">Auto-Generated</p>
                <p className="text-2xl font-bold text-primary">{stats?.autoGenerated || 0}</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4">
                <p className="text-sm text-muted-foreground">Manual</p>
                <p className="text-2xl font-bold text-purple-600">{stats?.manual || 0}</p>
              </CardContent>
            </Card>
          </>
        )}
      </div>

      {/* Controls */}
      <Card className="mb-6">
        <CardHeader>
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <CardTitle className="text-xl font-bold flex items-center gap-2">
                <Link2 className="h-5 w-5" />
                Internal Links
              </CardTitle>
              <CardDescription>
                Manage smart links between studies and blog posts
              </CardDescription>
            </div>
            <div className="flex gap-2 flex-wrap">
              <Button size="sm" onClick={() => setShowCreateDialog(true)}>
                <Plus className="h-4 w-4 mr-1" />
                Create Link
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => rebuildMutation.mutate()}
                disabled={rebuildMutation.isPending}
              >
                {rebuildMutation.isPending ? (
                  <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                ) : (
                  <RefreshCw className="h-4 w-4 mr-1" />
                )}
                Rebuild All Links
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {/* Filters */}
          <div className="flex flex-col sm:flex-row gap-4 mb-4">
            <div className="w-full sm:w-48">
              <Label className="text-xs mb-1 block">Content Type</Label>
              <Select
                value={typeFilter}
                onValueChange={(v) => {
                  setTypeFilter(v);
                  setPage(1);
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="All types" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  <SelectItem value="study">Study</SelectItem>
                  <SelectItem value="blog">Blog</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="w-full sm:w-48">
              <Label className="text-xs mb-1 block">Status</Label>
              <Select
                value={activeFilter}
                onValueChange={(v) => {
                  setActiveFilter(v);
                  setPage(1);
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="All statuses" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All</SelectItem>
                  <SelectItem value="true">Active</SelectItem>
                  <SelectItem value="false">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Table */}
          {linksLoading ? (
            <div className="space-y-2">
              {[1, 2, 3, 4, 5].map((i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          ) : links.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Link2 className="h-12 w-12 mx-auto mb-3 opacity-30" />
              <p>No links found. Create one or rebuild links.</p>
            </div>
          ) : (
            <div className="rounded-md border overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="min-w-[180px]">From</TableHead>
                    <TableHead className="min-w-[180px]">To</TableHead>
                    <TableHead className="min-w-[160px]">Anchor Text</TableHead>
                    <TableHead className="w-[70px]">Score</TableHead>
                    <TableHead className="w-[100px]">Type</TableHead>
                    <TableHead className="w-[60px]">Auto</TableHead>
                    <TableHead className="w-[70px]">Active</TableHead>
                    <TableHead className="w-[100px]">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {links.map((link) => (
                    <TableRow key={link.id}>
                      <TableCell>
                        <div className="flex items-center gap-1.5">
                          <Badge variant="outline" className="text-xs shrink-0">
                            {link.fromType}
                          </Badge>
                          <span
                            className="text-sm truncate max-w-[150px]"
                            title={link.fromTitle}
                          >
                            {link.fromTitle}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1.5">
                          <Badge variant="outline" className="text-xs shrink-0">
                            {link.toType}
                          </Badge>
                          <span
                            className="text-sm truncate max-w-[150px]"
                            title={link.toTitle}
                          >
                            {link.toTitle}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell>
                        {editingLinkId === link.id ? (
                          <div className="flex items-center gap-1">
                            <Input
                              value={editAnchorText}
                              onChange={(e) => setEditAnchorText(e.target.value)}
                              className="h-7 text-xs w-[140px]"
                              onKeyDown={(e) => {
                                if (e.key === "Enter") handleSaveAnchorText(link.id);
                                if (e.key === "Escape") cancelEditAnchor();
                              }}
                              autoFocus
                            />
                            <Button
                              size="icon"
                              variant="ghost"
                              className="h-6 w-6"
                              onClick={() => handleSaveAnchorText(link.id)}
                            >
                              <Check className="h-3 w-3" />
                            </Button>
                            <Button
                              size="icon"
                              variant="ghost"
                              className="h-6 w-6"
                              onClick={cancelEditAnchor}
                            >
                              <X className="h-3 w-3" />
                            </Button>
                          </div>
                        ) : (
                          <span
                            className="text-sm cursor-pointer hover:underline truncate max-w-[160px] block"
                            title={`Click to edit: ${link.anchorText}`}
                            onClick={() => startEditAnchor(link)}
                          >
                            {link.anchorText}
                          </span>
                        )}
                      </TableCell>
                      <TableCell>
                        <span className="text-sm font-mono">
                          {link.relevanceScore ?? "-"}
                        </span>
                      </TableCell>
                      <TableCell>
                        <span
                          className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${linkTypeBadgeVariant(link.linkType)}`}
                        >
                          {link.linkType || "N/A"}
                        </span>
                      </TableCell>
                      <TableCell>
                        {link.autoGenerated ? (
                          <Badge variant="secondary" className="text-xs">
                            Auto
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-xs">
                            Manual
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell>
                        <Switch
                          checked={link.isActive ?? false}
                          onCheckedChange={() => handleToggleActive(link)}
                          className="scale-75"
                        />
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1">
                          <Button
                            size="icon"
                            variant="ghost"
                            className="h-7 w-7"
                            title="Edit anchor text"
                            onClick={() => startEditAnchor(link)}
                          >
                            <Pencil className="h-3.5 w-3.5" />
                          </Button>
                          <Button
                            size="icon"
                            variant="ghost"
                            className="h-7 w-7 text-destructive hover:text-destructive"
                            title="Deactivate link"
                            onClick={() => deleteMutation.mutate(link.id)}
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between mt-4">
              <p className="text-sm text-muted-foreground">
                Showing {(page - 1) * limit + 1}-{Math.min(page * limit, totalLinks)} of{" "}
                {totalLinks} links
              </p>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page === 1}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <span className="text-sm">
                  Page {page} of {totalPages}
                </span>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Create Link Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Create Internal Link</DialogTitle>
            <DialogDescription>
              Add a manual link between two pieces of content.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label className="text-xs">From Type</Label>
                <Select
                  value={newLink.fromType}
                  onValueChange={(v) => setNewLink({ ...newLink, fromType: v })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {CONTENT_TYPE_OPTIONS.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-xs">From ID</Label>
                <Input
                  type="number"
                  value={newLink.fromId}
                  onChange={(e) => setNewLink({ ...newLink, fromId: e.target.value })}
                  placeholder="e.g. 42"
                />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label className="text-xs">To Type</Label>
                <Select
                  value={newLink.toType}
                  onValueChange={(v) => setNewLink({ ...newLink, toType: v })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {CONTENT_TYPE_OPTIONS.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-xs">To ID</Label>
                <Input
                  type="number"
                  value={newLink.toId}
                  onChange={(e) => setNewLink({ ...newLink, toId: e.target.value })}
                  placeholder="e.g. 15"
                />
              </div>
            </div>
            <div>
              <Label className="text-xs">Anchor Text</Label>
              <Input
                value={newLink.anchorText}
                onChange={(e) => setNewLink({ ...newLink, anchorText: e.target.value })}
                placeholder="Link text shown on page"
              />
            </div>
            <div>
              <Label className="text-xs">Context (optional)</Label>
              <Input
                value={newLink.context}
                onChange={(e) => setNewLink({ ...newLink, context: e.target.value })}
                placeholder="Surrounding text context"
              />
            </div>
            <div>
              <Label className="text-xs">Link Type</Label>
              <Select
                value={newLink.linkType}
                onValueChange={(v) => setNewLink({ ...newLink, linkType: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {LINK_TYPE_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={() => createMutation.mutate(newLink)}
              disabled={
                createMutation.isPending ||
                !newLink.fromId ||
                !newLink.toId ||
                !newLink.anchorText.trim()
              }
            >
              {createMutation.isPending && (
                <Loader2 className="h-4 w-4 mr-1 animate-spin" />
              )}
              Create
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AdminLayout>
  );
}
