import { pgTable, text, serial, integer, boolean, timestamp, primaryKey, varchar } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Consumer-friendly categorization model
export enum CategorizationModel {
  CONDITION = 'condition',
  BODY_SYSTEM = 'body_system',
  LIFE_STAGE = 'life_stage'
}

// Users table schema
export const users = pgTable("users", {
  id: text("id").primaryKey().notNull(), // Store Replit user ID
  email: text("email"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  profileImageUrl: text("profile_image_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// User preferences table schema
export const userPreferences = pgTable("user_preferences", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  categories: text("categories").array(),
  keywords: text("keywords").array(),
  authors: text("authors").array(),
  emailNotifications: boolean("email_notifications").default(true),
  notificationFrequency: text("notification_frequency").default("weekly"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Search history table schema
export const searchHistory = pgTable("search_history", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  searchQuery: text("search_query").notNull(),
  searchDate: timestamp("search_date").notNull().defaultNow(),
});

// User study interactions (saved/viewed studies)
export const userStudyInteractions = pgTable("user_study_interactions", {
  userId: text("user_id").notNull().references(() => users.id),
  studyId: integer("study_id").notNull().references(() => studies.id),
  isSaved: boolean("is_saved").default(false),
  viewCount: integer("view_count").default(0),
  lastViewed: timestamp("last_viewed").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.userId, table.studyId] }),
  }
});

// Notifications table schema
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  title: text("title").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(), // "study", "blog", "system"
  referenceId: integer("reference_id"), // Study or blog ID
  isRead: boolean("is_read").default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// User blog interactions (saved/viewed blogs)
export const userBlogInteractions = pgTable("user_blog_interactions", {
  userId: integer("user_id").notNull().references(() => users.id),
  blogId: integer("blog_id").notNull().references(() => blogArticles.id),
  isSaved: boolean("is_saved").default(false),
  viewCount: integer("view_count").default(0),
  lastViewed: timestamp("last_viewed").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.userId, table.blogId] }),
  }
});

// Studies table schema
export const studies = pgTable("studies", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  abstract: text("abstract").notNull(),
  authors: text("authors").notNull(),
  journal: text("journal").notNull(),
  publishDate: text("publish_date").notNull(), // Date when study was added to our site
  journalPublishDate: text("journal_publish_date"), // Original publication date in the journal
  category: text("category").notNull(),
  methods: text("methods"),
  results: text("results"),
  conclusion: text("conclusion"),
  doi: text("doi"),
  pdfUrl: text("pdf_url"),
  citationUrl: text("citation_url"),
  peerReviewed: boolean("peer_reviewed").notNull().default(true),
  // Media fields
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  // Support for multiple images and captions
  images: text("images").array(),
  imageCaptions: text("image_captions").array(),
  videoUrl: text("video_url"),
  audioUrl: text("audio_url"),
  // Automatically generated image information
  autoGeneratedImage: boolean("auto_generated_image").default(false),
  // Standardized summary fields for consistent display
  objective: text("objective"),
  methodsShort: text("methods_short"),
  resultsShort: text("results_short"),
  conclusionShort: text("conclusion_short"),
  summaryMarkdown: text("summary_markdown"),
  // Consumer-friendly categorization
  consumerCategories: text("consumer_categories"),
  // Additional fields for visualizations
  publishYear: integer("publish_year"),
  country: text("country"),
  region: text("region"),
  studyType: text("study_type"), // human, animal, in vitro
  outcome: text("outcome"), // positive, neutral, negative
  sampleSize: integer("sample_size"),
  duration: integer("duration"), // Study duration in days
  hasFullText: boolean("has_full_text").default(false),
  viewCount: integer("view_count").default(0),
  citationCount: integer("citation_count").default(0),
  // Source tracking information
  sourceUrl: text("source_url"),
  sourcePlatform: text("source_platform"),
  
  // === COMPREHENSIVE DOI ENRICHMENT FIELDS ===
  // Full text and content
  fullText: text("full_text"), // Complete article text when available
  fullTextHtml: text("full_text_html"), // HTML version of full text
  fullTextXml: text("full_text_xml"), // XML version from PMC
  supplementaryMaterials: text("supplementary_materials").array(), // URLs to supplementary files
  
  // Author information (enhanced)
  authorAffiliations: text("author_affiliations").array(), // Institutional affiliations
  correspondingAuthor: text("corresponding_author"), // Email/contact of corresponding author
  authorOrcids: text("author_orcids").array(), // ORCID IDs for authors
  authorInstitutions: text("author_institutions").array(), // Institution names
  
  // Publication metadata (enhanced)
  journalIssn: text("journal_issn"), // Journal ISSN
  journalEissn: text("journal_e_issn"), // Electronic ISSN
  journalImpactFactor: text("journal_impact_factor"), // Impact factor if available
  volume: text("volume"), // Journal volume
  issue: text("issue"), // Journal issue
  pages: text("pages"), // Page range (e.g., "123-145")
  
  // Licensing and copyright
  license: text("license"), // License type (CC-BY, etc.)
  licenseUrl: text("license_url"), // URL to license terms
  copyright: text("copyright"), // Copyright statement
  openAccess: boolean("open_access").default(false), // Is open access
  
  // Citations and references
  referencesJson: text("references_json"), // Complete reference list as JSON
  citedByCount: integer("cited_by_count").default(0), // Number of citing papers
  citingPapers: text("citing_papers").array(), // DOIs of papers that cite this one
  relatedPapers: text("related_papers").array(), // DOIs of related papers
  
  // Research funding and grants
  fundingSources: text("funding_sources").array(), // Funding organizations
  grantNumbers: text("grant_numbers").array(), // Grant/award numbers
  fundingCountries: text("funding_countries").array(), // Countries providing funding
  
  // Clinical and research specifics
  clinicalTrialNumbers: text("clinical_trial_numbers").array(), // NCT numbers, etc.
  studyRegistry: text("study_registry"), // Registry where study is registered
  ethicsApproval: text("ethics_approval"), // Ethics committee approval info
  dataAvailability: text("data_availability"), // Data availability statement
  conflictOfInterest: text("conflict_of_interest"), // COI statement
  
  // Quality and validation indicators
  peerReviewType: text("peer_review_type"), // Type of peer review
  retracted: boolean("retracted").default(false), // Is the paper retracted
  retractionReason: text("retraction_reason"), // Reason for retraction if applicable
  corrections: text("corrections").array(), // Any published corrections
  
  // Subject classification
  meshTerms: text("mesh_terms").array(), // Medical Subject Headings
  keywords: text("keywords").array(), // Author-provided keywords
  subjectAreas: text("subject_areas").array(), // Subject classifications
  researchFields: text("research_fields").array(), // Research field classifications
  
  // Media and figures (enhanced)
  figureUrls: text("figure_urls").array(), // URLs to all figures
  figureCaptions: text("figure_captions").array(), // Captions for all figures
  tableData: text("table_data"), // Structured table data as JSON
  graphicalAbstract: text("graphical_abstract"), // URL to graphical abstract
  
  // External identifiers
  pmid: text("pmid"), // PubMed ID
  pmcid: text("pmc_id"), // PMC ID
  semanticScholarId: text("semantic_scholar_id"), // Semantic Scholar paper ID
  crossrefId: text("crossref_id"), // CrossRef ID
  arxivId: text("arxiv_id"), // arXiv ID if applicable
  
  // Language and accessibility
  language: text("language").default("en"), // Publication language
  abstractLanguages: text("abstract_languages").array(), // Available abstract languages
  fullTextLanguages: text("full_text_languages").array(), // Available full text languages
  
  // Update tracking
  lastEnriched: timestamp("last_enriched"), // When DOI enrichment was last performed
  enrichmentSources: text("enrichment_sources").array(), // Which APIs provided data
  enrichmentQuality: integer("enrichment_quality").default(0), // 0-100 completeness score
  
  // === CHATGPT AI ENHANCEMENT FIELDS ===
  // Consumer-friendly content
  simplifiedExplanation: text("simplified_explanation"), // Plain language explanation
  plainLanguageTitle: text("plain_language_title"), // SEO-optimized consumer-friendly title
  seoTitle: text("seo_title"), // Search-optimized title
  seoDescription: text("seo_description"), // Meta description for SEO
  seoKeywords: text("seo_keywords").array(), // SEO keyword array
  
  // AI processing tracking
  enhancedWithAI: boolean("enhanced_with_ai").default(false), // Has been AI enhanced
  lastAIEnhanced: timestamp("last_ai_enhanced"), // When AI enhancement was performed
  
  // Smart tagging system for filtering and search
  healthBenefits: text("health_benefits").array(), // Health benefit tags
  healthConditions: text("health_conditions").array(), // Health condition tags
  bodySystems: text("body_systems").array(), // Body system tags
  lifeStages: text("life_stages").array(), // Life stage tags
  studyTypes: text("study_types").array(), // Study type tags
  mechanisms: text("mechanisms").array(), // Mechanism tags
  
  // Enhanced image generation
  aiGeneratedImage: boolean("ai_generated_image").default(false), // AI-generated image
  imagePrompt: text("image_prompt"), // Prompt used for image generation
  imageGenerationDate: timestamp("image_generation_date"), // When image was generated
  
  // User experience enhancements
  readingLevel: text("reading_level"), // Content difficulty level
  estimatedReadTime: integer("estimated_read_time"), // Reading time in minutes
  popularityScore: integer("popularity_score").default(0), // User engagement metrics
  
  // Advanced research details
  deliveryMethods: text("delivery_methods").array(), // How hydrogen was administered
  dosageInformation: text("dosage_information"), // Dosage details
  studyDurationDays: integer("study_duration_days"), // Length of study in days
  participantCount: integer("participant_count"), // Number of participants
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Categories table schema
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  icon: text("icon"),
  studyCount: integer("study_count").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Body systems table schema
export const bodySystems = pgTable("body_systems", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  icon: text("icon"),
  slug: text("slug").notNull().unique(),
  displayOrder: integer("display_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Health conditions table schema
export const healthConditions = pgTable("health_conditions", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  bodySystemId: integer("body_system_id").notNull().references(() => bodySystems.id),
  slug: text("slug").notNull().unique(),
  displayOrder: integer("display_order").notNull().default(0),
  studyCount: integer("study_count").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Study health conditions mapping table
export const studyHealthConditions = pgTable("study_health_conditions", {
  studyId: integer("study_id").notNull().references(() => studies.id),
  healthConditionId: integer("health_condition_id").notNull().references(() => healthConditions.id),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.studyId, table.healthConditionId] }),
  }
});

// Curated collections table
export const studyCollections = pgTable("study_collections", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  slug: text("slug").notNull().unique(),
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  featuredOrder: integer("featured_order").default(0),
  isPublished: boolean("is_published").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Collection studies mapping table
export const collectionStudies = pgTable("collection_studies", {
  collectionId: integer("collection_id").notNull().references(() => studyCollections.id),
  studyId: integer("study_id").notNull().references(() => studies.id),
  displayOrder: integer("display_order").default(0),
  addedAt: timestamp("added_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.collectionId, table.studyId] }),
  }
});

// Newsletter subscriptions table schema
export const newsletters = pgTable("newsletters", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Educational resources table - for Learn section
export const educationalResources = pgTable("educational_resources", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  content: text("content").notNull(),
  contentMarkdown: text("content_markdown").notNull(),
  resourceType: text("resource_type").notNull(), // glossary, faq, tutorial, guide
  featuredOrder: integer("featured_order").default(0),
  viewCount: integer("view_count").default(0),
  isPublished: boolean("is_published").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Glossary terms table
export const glossaryTerms = pgTable("glossary_terms", {
  id: serial("id").primaryKey(),
  term: text("term").notNull().unique(),
  definition: text("definition").notNull(),
  longDefinition: text("long_definition"),
  references: text("references"),
  relatedTerms: text("related_terms").array(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// FAQ table
export const faqItems = pgTable("faq_items", {
  id: serial("id").primaryKey(),
  question: text("question").notNull(),
  answer: text("answer").notNull(), 
  answerMarkdown: text("answer_markdown").notNull(),
  category: text("category").notNull(), // general, scientific, application
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Contact form messages table schema
export const contactMessages = pgTable("contact_messages", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  message: text("message").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Table for tracking scraped sources to avoid duplicates
export const scrapedSources = pgTable("scraped_sources", {
  id: serial("id").primaryKey(),
  sourceUrl: text("source_url").notNull(),
  sourcePlatform: text("source_platform").notNull(),
  studyId: integer("study_id").notNull().references(() => studies.id),
  scrapedAt: timestamp("scraped_at").notNull().defaultNow(),
});

// Study review status enum values
export const ReviewStatus = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected'
} as const;

// Study review queue table for managing the study approval process
export const studyReviewQueue = pgTable("study_review_queue", {
  id: serial("id").primaryKey(),
  // External study ID (from source database like PubMed, CrossRef, etc.)
  externalId: text("external_id").notNull(),
  // DOI for duplicate checking
  doi: text("doi"),
  title: text("title").notNull(),
  abstract: text("abstract").notNull(),
  authors: text("authors").notNull(),
  journal: text("journal").notNull(),
  publishDate: text("publish_date"),
  journalPublishDate: text("journal_publish_date"),
  category: text("category").notNull(),
  // Source information 
  sourceUrl: text("source_url"),
  sourcePlatform: text("source_platform").notNull(),
  // Review status
  status: text("status").notNull().default('pending'),
  // Who saved the study for review and who approved/rejected it
  savedByUserId: text("saved_by_user_id").references(() => users.id),
  reviewedByUserId: text("reviewed_by_user_id").references(() => users.id),
  // Notes added during the review process
  reviewNotes: text("review_notes"),
  // Whether this entry is a duplicate of an existing study
  isDuplicate: boolean("is_duplicate").default(false),
  // If it's a duplicate, this references the original study
  duplicateOfStudyId: integer("duplicate_of_study_id").references(() => studies.id),
  // Timestamps
  savedAt: timestamp("saved_at").notNull().defaultNow(),
  reviewedAt: timestamp("reviewed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Blog articles table schema
export const blogArticles = pgTable("blog_articles", {
  id: serial("id").primaryKey(),
  studyId: integer("study_id").notNull().references(() => studies.id),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  summary: text("summary").notNull(),
  content: text("content").notNull(),
  quickInsights: text("quick_insights"),
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  readingLevel: text("reading_level").default("general"),
  articleType: text("article_type"),
  isPublished: boolean("is_published").default(false),
  editorNotes: text("editor_notes"),
  viewCount: integer("view_count").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Create insertion schemas and types
export const insertStudySchema = createInsertSchema(studies).omit({ id: true, createdAt: true });
export const insertCategorySchema = createInsertSchema(categories).omit({ id: true, createdAt: true });
export const insertNewsletterSchema = createInsertSchema(newsletters).omit({ id: true, createdAt: true });
export const insertContactSchema = createInsertSchema(contactMessages).omit({ id: true, createdAt: true });
export const insertBlogArticleSchema = createInsertSchema(blogArticles).omit({ id: true, createdAt: true, updatedAt: true, viewCount: true });
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true, updatedAt: true });
export const insertUserPreferencesSchema = createInsertSchema(userPreferences).omit({ id: true, createdAt: true, updatedAt: true });
export const insertSearchHistorySchema = createInsertSchema(searchHistory).omit({ id: true, searchDate: true });
export const insertNotificationSchema = createInsertSchema(notifications).omit({ id: true, createdAt: true });
export const insertUserStudyInteractionSchema = createInsertSchema(userStudyInteractions).omit({ createdAt: true });
export const insertUserBlogInteractionSchema = createInsertSchema(userBlogInteractions).omit({ createdAt: true });
export const insertEducationalResourceSchema = createInsertSchema(educationalResources).omit({ id: true, createdAt: true, updatedAt: true, viewCount: true });
export const insertGlossaryTermSchema = createInsertSchema(glossaryTerms).omit({ id: true, createdAt: true, updatedAt: true });
export const insertFaqItemSchema = createInsertSchema(faqItems).omit({ id: true, createdAt: true, updatedAt: true });
export const insertStudyCollectionSchema = createInsertSchema(studyCollections).omit({ id: true, createdAt: true, updatedAt: true });
export const insertCollectionStudySchema = createInsertSchema(collectionStudies).omit({ addedAt: true });
export const insertStudyReviewQueueSchema = createInsertSchema(studyReviewQueue).omit({ 
  id: true, 
  savedAt: true, 
  reviewedAt: true, 
  createdAt: true 
});

// Types for insertion
export type InsertStudy = z.infer<typeof insertStudySchema>;
export type InsertCategory = z.infer<typeof insertCategorySchema>;
export type InsertNewsletter = z.infer<typeof insertNewsletterSchema>;
export type InsertContact = z.infer<typeof insertContactSchema>;
export type InsertBlogArticle = z.infer<typeof insertBlogArticleSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertUserPreferences = z.infer<typeof insertUserPreferencesSchema>;
export type InsertSearchHistory = z.infer<typeof insertSearchHistorySchema>;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type InsertUserStudyInteraction = z.infer<typeof insertUserStudyInteractionSchema>;
export type InsertUserBlogInteraction = z.infer<typeof insertUserBlogInteractionSchema>;
export type InsertEducationalResource = z.infer<typeof insertEducationalResourceSchema>;
export type InsertGlossaryTerm = z.infer<typeof insertGlossaryTermSchema>;
export type InsertFaqItem = z.infer<typeof insertFaqItemSchema>;
export type InsertStudyCollection = z.infer<typeof insertStudyCollectionSchema>;
export type InsertCollectionStudy = z.infer<typeof insertCollectionStudySchema>;
export type InsertStudyReviewQueue = z.infer<typeof insertStudyReviewQueueSchema>;

// Types for selection
export type Study = typeof studies.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Newsletter = typeof newsletters.$inferSelect;
export type BlogArticle = typeof blogArticles.$inferSelect;
export type User = typeof users.$inferSelect;
export type UserPreferences = typeof userPreferences.$inferSelect;
export type SearchHistory = typeof searchHistory.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type UserStudyInteraction = typeof userStudyInteractions.$inferSelect;
export type UserBlogInteraction = typeof userBlogInteractions.$inferSelect;
export type EducationalResource = typeof educationalResources.$inferSelect;
export type GlossaryTerm = typeof glossaryTerms.$inferSelect;
export type FaqItem = typeof faqItems.$inferSelect;
export type StudyCollection = typeof studyCollections.$inferSelect;
export type CollectionStudy = typeof collectionStudies.$inferSelect;
export type StudyReviewQueue = typeof studyReviewQueue.$inferSelect;

// Chat conversations table schema
export const conversations = pgTable("conversations", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  title: text("title").default("New Conversation"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Chat messages table schema
export const chatMessages = pgTable("chat_messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id").notNull().references(() => conversations.id),
  role: varchar("role", { length: 20 }).notNull(), // 'user' or 'assistant'
  content: text("content").notNull(),
  timestamp: timestamp("timestamp").notNull().defaultNow(),
});

// Chat feedback table schema
export const chatFeedback = pgTable("chat_feedback", {
  id: serial("id").primaryKey(),
  messageId: integer("message_id").notNull().references(() => chatMessages.id),
  userId: integer("user_id").references(() => users.id),
  rating: integer("rating").notNull(), // 1 (thumbs down) or 5 (thumbs up)
  comment: text("comment"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Popular questions table schema
export const popularQuestions = pgTable("popular_questions", {
  id: serial("id").primaryKey(),
  question: text("question").notNull().unique(),
  category: text("category").notNull(),
  displayOrder: integer("display_order").default(0),
  clickCount: integer("click_count").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Create insertion schemas for chat tables
export const insertConversationSchema = createInsertSchema(conversations).omit({ id: true, createdAt: true, updatedAt: true });
export const insertChatMessageSchema = createInsertSchema(chatMessages).omit({ id: true, timestamp: true });
export const insertChatFeedbackSchema = createInsertSchema(chatFeedback).omit({ id: true, createdAt: true });
export const insertPopularQuestionSchema = createInsertSchema(popularQuestions).omit({ id: true, clickCount: true, createdAt: true });

// Types for chat tables
export type Conversation = typeof conversations.$inferSelect;
export type ChatMessage = typeof chatMessages.$inferSelect;
export type ChatFeedback = typeof chatFeedback.$inferSelect;
export type PopularQuestion = typeof popularQuestions.$inferSelect;
export type InsertConversation = z.infer<typeof insertConversationSchema>;
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
export type InsertChatFeedback = z.infer<typeof insertChatFeedbackSchema>;
export type InsertPopularQuestion = z.infer<typeof insertPopularQuestionSchema>;

// Keyword monitoring tables
export const keywords = pgTable("keywords", {
  id: serial("id").primaryKey(),
  term: text("term").notNull(),
  category: text("category").default("general").notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  lastSearched: timestamp("last_searched"),
  matchCount: integer("match_count").default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const excludedKeywords = pgTable("excluded_keywords", {
  id: serial("id").primaryKey(),
  term: text("term").notNull(),
  reason: text("reason"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const keywordGroups = pgTable("keyword_groups", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const keywordGroupMappings = pgTable("keyword_group_mappings", {
  id: serial("id").primaryKey(),
  keywordId: integer("keyword_id").references(() => keywords.id, { onDelete: "cascade" }).notNull(),
  groupId: integer("group_id").references(() => keywordGroups.id, { onDelete: "cascade" }).notNull(),
});

export const monitorSchedule = pgTable("monitor_schedule", {
  id: serial("id").primaryKey(),
  enabled: boolean("enabled").default(false).notNull(),
  frequency: text("frequency").default("daily").notNull(),
  time: text("time").default("00:00").notNull(),
  days: text("days").array(),
  sources: text("sources").array(),
  lastRun: timestamp("last_run"),
  nextRun: timestamp("next_run"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const monitorResults = pgTable("monitor_results", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  abstract: text("abstract"),
  authors: text("authors"),
  journal: text("journal"),
  publishDate: text("publish_date"),
  doi: text("doi"),
  url: text("url"),
  matchedKeywords: text("matched_keywords").array(),
  status: text("status").default("pending").notNull(),
  source: text("source").notNull(),
  foundAt: timestamp("found_at").defaultNow().notNull(),
  reviewedBy: text("reviewed_by"),
  reviewedAt: timestamp("reviewed_at"),
  notes: text("notes"),
});

// Create insertion schemas for keyword monitoring
export const insertKeywordSchema = createInsertSchema(keywords).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true, 
  lastSearched: true,
  matchCount: true
});
export const insertExcludedKeywordSchema = createInsertSchema(excludedKeywords).omit({ id: true, createdAt: true });
export const insertKeywordGroupSchema = createInsertSchema(keywordGroups).omit({ id: true, createdAt: true });
export const insertKeywordGroupMappingSchema = createInsertSchema(keywordGroupMappings).omit({ id: true });
export const insertMonitorResultSchema = createInsertSchema(monitorResults).omit({ 
  id: true, 
  foundAt: true, 
  reviewedAt: true 
});
export const insertMonitorScheduleSchema = createInsertSchema(monitorSchedule).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  lastRun: true,
  nextRun: true
});

// Types for keyword monitoring
export type Keyword = typeof keywords.$inferSelect;
export type ExcludedKeyword = typeof excludedKeywords.$inferSelect;
export type KeywordGroup = typeof keywordGroups.$inferSelect;
export type KeywordGroupMapping = typeof keywordGroupMappings.$inferSelect;
export type MonitorSchedule = typeof monitorSchedule.$inferSelect;
export type MonitorResult = typeof monitorResults.$inferSelect;
export type InsertKeyword = z.infer<typeof insertKeywordSchema>;
export type InsertExcludedKeyword = z.infer<typeof insertExcludedKeywordSchema>;
export type InsertKeywordGroup = z.infer<typeof insertKeywordGroupSchema>;
export type InsertKeywordGroupMapping = z.infer<typeof insertKeywordGroupMappingSchema>;
export type InsertMonitorSchedule = z.infer<typeof insertMonitorScheduleSchema>;
export type InsertMonitorResult = z.infer<typeof insertMonitorResultSchema>;
