import { pgTable, text, serial, integer, boolean, timestamp, primaryKey, varchar, unique, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Consumer-friendly categorization model
export enum CategorizationModel {
  CONDITION = 'condition',
  BODY_SYSTEM = 'body_system',
  LIFE_STAGE = 'life_stage'
}

// Users table schema
export const users = pgTable("users", {
  id: text("id").primaryKey().notNull(), // Store Replit user ID
  email: text("email"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  profileImageUrl: text("profile_image_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// User preferences table schema
export const userPreferences = pgTable("user_preferences", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id),
  categories: text("categories").array(),
  keywords: text("keywords").array(),
  authors: text("authors").array(),
  emailNotifications: boolean("email_notifications").default(true),
  notificationFrequency: text("notification_frequency").default("weekly"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Search history table schema
export const searchHistory = pgTable("search_history", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id),
  searchQuery: text("search_query").notNull(),
  searchDate: timestamp("search_date").notNull().defaultNow(),
});

// User study interactions (saved/viewed studies)
export const userStudyInteractions = pgTable("user_study_interactions", {
  userId: text("user_id").notNull().references(() => users.id),
  studyId: integer("study_id").notNull().references(() => studies.id),
  isSaved: boolean("is_saved").default(false),
  viewCount: integer("view_count").default(0),
  lastViewed: timestamp("last_viewed").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.userId, table.studyId] }),
  }
});

// Notifications table schema
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id),
  title: text("title").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(), // "study", "blog", "system"
  referenceId: integer("reference_id"), // Study or blog ID
  isRead: boolean("is_read").default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// User blog interactions (saved/viewed blogs)
export const userBlogInteractions = pgTable("user_blog_interactions", {
  userId: text("user_id").notNull().references(() => users.id),
  blogId: integer("blog_id").notNull().references(() => blogArticles.id),
  isSaved: boolean("is_saved").default(false),
  viewCount: integer("view_count").default(0),
  lastViewed: timestamp("last_viewed").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.userId, table.blogId] }),
  }
});

// Studies table schema
export const studies = pgTable("studies", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  abstract: text("abstract").notNull(),
  authors: text("authors").notNull(),
  journal: text("journal").notNull(),
  publishDate: text("publish_date").notNull(), // Date when study was added to our site
  journalPublishDate: text("journal_publish_date"), // Original publication date in the journal
  category: text("category").notNull(),
  methods: text("methods"),
  results: text("results"),
  conclusion: text("conclusion"),
  doi: text("doi"),
  url: text("url"),
  pdfUrl: text("pdf_url"),
  citationUrl: text("citation_url"),
  peerReviewed: boolean("peer_reviewed").notNull().default(true),
  // Media fields
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  // Support for multiple images and captions
  images: text("images").array(),
  imageCaptions: text("image_captions").array(),
  videoUrl: text("video_url"),
  audioUrl: text("audio_url"),
  // Automatically generated image information
  autoGeneratedImage: boolean("auto_generated_image").default(false),
  // Standardized summary fields for consistent display
  objective: text("objective"),
  methodsShort: text("methods_short"),
  resultsShort: text("results_short"),
  conclusionShort: text("conclusion_short"),
  summaryMarkdown: text("summary_markdown"),
  // Consumer-friendly categorization
  consumerCategories: text("consumer_categories"),
  // Additional fields for visualizations
  publishYear: integer("publish_year"),
  country: text("country"),
  region: text("region"),
  studyType: text("study_type"), // human, animal, in vitro
  outcome: text("outcome"), // positive, neutral, negative
  sampleSize: integer("sample_size"),
  duration: integer("duration"), // Study duration in days
  hasFullText: boolean("has_full_text").default(false),
  viewCount: integer("view_count").default(0),
  citationCount: integer("citation_count").default(0),
  // Source tracking information
  sourceUrl: text("source_url"),
  sourcePlatform: text("source_platform"),
  
  // Only include fields that exist in the database
  keywords: text("keywords").array(), // Author-provided keywords
  plainLanguageTitle: text("plain_language_title"), // SEO-optimized consumer-friendly title
  slug: text("slug"), // URL-friendly slug generated from plain language title
  
  // Authentic research data fields from PubMed/CrossRef APIs
  authorAffiliations: text("author_affiliations"), // Real institutional affiliations
  fundingSources: text("funding_sources"), // Actual grant information
  statisticalMethods: text("statistical_methods"), // Research methodology details
  ethicalApproval: text("ethical_approval"), // Ethics committee information
  fullText: text("full_text"), // Full research paper content when available
  
  // SEO Enhancement Fields
  canonicalUrl: text("canonical_url"), // Prevent duplicate content issues
  metaTitle: text("meta_title"), // SEO-optimized title (60 chars)
  metaDescription: text("meta_description"), // SEO description (160 chars)
  schemaOrg: text("schema_org"), // JSON-LD structured data for search engines
  ogTitle: text("og_title"), // Open Graph title for social sharing
  ogDescription: text("og_description"), // Open Graph description
  ogImage: text("og_image"), // Open Graph image URL
  twitterCard: text("twitter_card"), // Twitter card type
  twitterTitle: text("twitter_title"), // Twitter card title
  twitterDescription: text("twitter_description"), // Twitter card description
  twitterImage: text("twitter_image"), // Twitter card image
  lastModified: timestamp("last_modified"), // For sitemap generation
  priority: text("priority"), // Sitemap priority (0.0-1.0)
  changeFrequency: text("change_frequency"), // Sitemap update frequency
  structuredData: text("structured_data"), // JSONB field for AI-readable structured data
  
  // Academic Enhancement Fields
  academicSchema: text("academic_schema"), // Scholar.org structured data
  citationFormats: text("citation_formats"), // JSON with multiple citation formats (APA, MLA, etc.)
  impactMetrics: text("impact_metrics"), // Academic ranking and impact scores
  peerReviewStatus: text("peer_review_status"), // Peer review credibility status
  conflictOfInterest: text("conflict_of_interest"), // Trust signal declarations
  
  // AI Comprehension Fields
  hierarchicalStructure: text("hierarchical_structure"), // H1, H2, H3 tag structure
  semanticHtml: text("semantic_html"), // Semantic HTML equivalents
  entityRecognition: text("entity_recognition"), // JSON of recognized entities (people, places, medical terms)
  conceptRelationships: text("concept_relationships"), // Linked data relationships
  questionAnswerPairs: text("question_answer_pairs"), // Q&A pairs for AI training
  summary50Words: text("summary_50_words"), // 50-word summary
  summary100Words: text("summary_100_words"), // 100-word summary
  summary200Words: text("summary_200_words"), // 200-word summary
  semanticKeywords: text("semantic_keywords").array(), // LSI keywords for SEO
  topicalRelevance: integer("topical_relevance"), // Score for topical authority (0-100)
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (table) => {
  return {
    // Performance indexes for SEO and search
    slugIdx: index("studies_slug_idx").on(table.slug),
    canonicalUrlIdx: index("studies_canonical_url_idx").on(table.canonicalUrl),
    publishYearIdx: index("studies_publish_year_idx").on(table.publishYear),
    categoryIdx: index("studies_category_idx").on(table.category),
    viewCountIdx: index("studies_view_count_idx").on(table.viewCount),
    lastModifiedIdx: index("studies_last_modified_idx").on(table.lastModified),
  }
});

// Categories table schema
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  icon: text("icon"),
  studyCount: integer("study_count").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Study categories junction table for many-to-many relationships
export const studyCategories = pgTable("study_categories", {
  id: serial("id").primaryKey(),
  studyId: integer("study_id").notNull().references(() => studies.id, { onDelete: "cascade" }),
  categoryId: integer("category_id").notNull().references(() => categories.id, { onDelete: "cascade" }),
  isPrimary: boolean("is_primary").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Body systems table schema
export const bodySystems = pgTable("body_systems", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  icon: text("icon"),
  slug: text("slug").notNull().unique(),
  displayOrder: integer("display_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Health conditions table schema
export const healthConditions = pgTable("health_conditions", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  bodySystemId: integer("body_system_id").notNull().references(() => bodySystems.id),
  slug: text("slug").notNull().unique(),
  displayOrder: integer("display_order").notNull().default(0),
  studyCount: integer("study_count").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Study health conditions mapping table
export const studyHealthConditions = pgTable("study_health_conditions", {
  studyId: integer("study_id").notNull().references(() => studies.id),
  healthConditionId: integer("health_condition_id").notNull().references(() => healthConditions.id),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.studyId, table.healthConditionId] }),
  }
});

// Curated collections table
export const studyCollections = pgTable("study_collections", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  description: text("description").notNull(),
  slug: text("slug").notNull().unique(),
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  featuredOrder: integer("featured_order").default(0),
  isPublished: boolean("is_published").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Consumer categories table for categorization system
export const consumerCategories = pgTable("consumer_categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  categoryModel: text("category_model").notNull(), // 'condition', 'body_system', 'life_stage'
  slug: text("slug").notNull().unique(),
  studyCount: integer("study_count").default(0),
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Collection studies mapping table
export const collectionStudies = pgTable("collection_studies", {
  collectionId: integer("collection_id").notNull().references(() => studyCollections.id),
  studyId: integer("study_id").notNull().references(() => studies.id),
  displayOrder: integer("display_order").default(0),
  addedAt: timestamp("added_at").notNull().defaultNow(),
}, (table) => {
  return {
    pk: primaryKey({ columns: [table.collectionId, table.studyId] }),
  }
});

// Newsletter subscriptions table schema
export const newsletters = pgTable("newsletters", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Educational resources table - for Learn section
export const educationalResources = pgTable("educational_resources", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  content: text("content").notNull(),
  contentMarkdown: text("content_markdown").notNull(),
  resourceType: text("resource_type").notNull(), // glossary, faq, tutorial, guide
  featuredOrder: integer("featured_order").default(0),
  viewCount: integer("view_count").default(0),
  isPublished: boolean("is_published").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Glossary terms table
export const glossaryTerms = pgTable("glossary_terms", {
  id: serial("id").primaryKey(),
  term: text("term").notNull().unique(),
  definition: text("definition").notNull(),
  longDefinition: text("long_definition"),
  references: text("references"),
  relatedTerms: text("related_terms").array(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// FAQ table
export const faqItems = pgTable("faq_items", {
  id: serial("id").primaryKey(),
  question: text("question").notNull(),
  answer: text("answer").notNull(), 
  answerMarkdown: text("answer_markdown").notNull(),
  category: text("category").notNull(), // general, scientific, application
  displayOrder: integer("display_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Contact form messages table schema
export const contactMessages = pgTable("contact_messages", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  message: text("message").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// SEO Metadata table for centralized SEO management
export const seoMetadata = pgTable("seo_metadata", {
  id: serial("id").primaryKey(),
  entityType: text("entity_type").notNull(), // 'study', 'blog', 'article', 'page'
  entityId: integer("entity_id").notNull(), // Foreign key to respective table
  
  // SEO Directives
  robots: text("robots").default("index, follow"), // Index/follow directives
  robotsNoIndex: boolean("robots_no_index").default(false),
  robotsNoFollow: boolean("robots_no_follow").default(false),
  
  // International SEO
  alternateLanguages: text("alternate_languages"), // JSON array of hreflang tags
  
  // Link Management
  internalLinks: text("internal_links").array(), // Array of related content URLs
  externalLinks: text("external_links").array(), // Authoritative source URLs
  
  // Keyword and Relevance
  semanticKeywords: text("semantic_keywords").array(), // LSI keywords for SEO
  topicalRelevance: integer("topical_relevance").default(50), // Score 0-100 for topical authority
  keywordDensity: text("keyword_density"), // JSON object with keyword frequency data
  
  // Search Engine Performance
  clickThroughRate: text("click_through_rate"), // CTR data from search console
  averagePosition: text("average_position"), // Average SERP position
  impressions: integer("impressions").default(0), // Search impressions count
  clicks: integer("clicks").default(0), // Search clicks count
  
  // AI and ML Optimization
  aiOptimizationScore: integer("ai_optimization_score").default(0), // 0-100 score
  contentQualityScore: integer("content_quality_score").default(0), // 0-100 score
  readabilityScore: integer("readability_score").default(0), // 0-100 score
  sentimentAnalysis: text("sentiment_analysis"), // JSON with sentiment data
  
  // Schema Markup
  richSnippetType: text("rich_snippet_type"), // Type of rich snippet (FAQ, HowTo, etc.)
  schemaMarkup: text("schema_markup"), // Full schema.org JSON-LD
  
  // Social Media Metrics
  socialMediaEngagement: text("social_media_engagement"), // JSON with platform-specific metrics
  viralityScore: integer("virality_score").default(0), // 0-100 viral potential
  
  // Content Freshness
  lastContentUpdate: timestamp("last_content_update"),
  contentUpdateFrequency: text("content_update_frequency"), // daily, weekly, monthly, yearly
  nextScheduledUpdate: timestamp("next_scheduled_update"),
  
  // Performance Metrics
  pageSpeed: integer("page_speed"), // Lighthouse score
  mobileFriendly: boolean("mobile_friendly").default(true),
  coreWebVitals: text("core_web_vitals"), // JSON with LCP, FID, CLS scores
  
  // Tracking
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => {
  return {
    // Composite index for entity lookups
    entityIdx: index("seo_metadata_entity_idx").on(table.entityType, table.entityId),
    // Performance indexes
    relevanceIdx: index("seo_metadata_relevance_idx").on(table.topicalRelevance),
    qualityIdx: index("seo_metadata_quality_idx").on(table.contentQualityScore),
  }
});

// Table for tracking scraped sources to avoid duplicates
export const scrapedSources = pgTable("scraped_sources", {
  id: serial("id").primaryKey(),
  sourceUrl: text("source_url").notNull(),
  sourcePlatform: text("source_platform").notNull(),
  studyId: integer("study_id").notNull().references(() => studies.id),
  scrapedAt: timestamp("scraped_at").notNull().defaultNow(),
});

// Study review status enum values
export const ReviewStatus = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected'
} as const;

// Study review queue table for managing the study approval process
export const studyReviewQueue = pgTable("study_review_queue", {
  id: serial("id").primaryKey(),
  // External study ID (from source database like PubMed, CrossRef, etc.)
  externalId: text("external_id").notNull(),
  // DOI for duplicate checking
  doi: text("doi"),
  title: text("title").notNull(),
  abstract: text("abstract").notNull(),
  authors: text("authors").notNull(),
  journal: text("journal").notNull(),
  publishDate: text("publish_date"),
  journalPublishDate: text("journal_publish_date"),
  category: text("category").notNull(),
  // Source information 
  sourceUrl: text("source_url"),
  sourcePlatform: text("source_platform").notNull(),
  // Review status
  status: text("status").notNull().default('pending'),
  // Who saved the study for review and who approved/rejected it
  savedByUserId: text("saved_by_user_id").references(() => users.id),
  reviewedByUserId: text("reviewed_by_user_id").references(() => users.id),
  // Notes added during the review process
  reviewNotes: text("review_notes"),
  // Whether this entry is a duplicate of an existing study
  isDuplicate: boolean("is_duplicate").default(false),
  // If it's a duplicate, this references the original study
  duplicateOfStudyId: integer("duplicate_of_study_id").references(() => studies.id),
  // Timestamps
  savedAt: timestamp("saved_at").notNull().defaultNow(),
  reviewedAt: timestamp("reviewed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Blog articles table schema
export const blogArticles = pgTable("blog_articles", {
  id: serial("id").primaryKey(),
  studyId: integer("study_id").notNull().references(() => studies.id),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  summary: text("summary").notNull(),
  content: text("content").notNull(),
  quickInsights: text("quick_insights"),
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  readingLevel: text("reading_level").default("general"),
  articleType: text("article_type"),
  isPublished: boolean("is_published").default(false),
  editorNotes: text("editor_notes"),
  viewCount: integer("view_count").default(0),
  
  // SEO Enhancement Fields for Blogs
  canonicalUrl: text("canonical_url"),
  metaTitle: text("meta_title"),
  metaDescription: text("meta_description"),
  schemaOrg: text("schema_org"), // Article schema JSON-LD
  breadcrumbs: text("breadcrumbs"), // Navigation structure JSON
  authorBio: text("author_bio"), // For E-A-T (Expertise, Authority, Trust)
  lastReviewed: timestamp("last_reviewed"), // Content freshness indicator
  faqSchema: text("faq_schema"), // FAQ structured data if applicable
  socialShares: integer("social_shares").default(0), // Track social engagement
  ogTitle: text("og_title"),
  ogDescription: text("og_description"),
  ogImage: text("og_image"),
  twitterCard: text("twitter_card"),
  twitterTitle: text("twitter_title"),
  twitterDescription: text("twitter_description"),
  
  // AI Comprehension Fields for Blogs
  hierarchicalStructure: text("hierarchical_structure"),
  entityRecognition: text("entity_recognition"),
  semanticKeywords: text("semantic_keywords").array(),
  questionAnswerPairs: text("question_answer_pairs"),
  summary50Words: text("summary_50_words"),
  summary100Words: text("summary_100_words"),
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => {
  return {
    // Performance indexes for blog SEO
    slugIdx: index("blog_articles_slug_idx").on(table.slug),
    canonicalUrlIdx: index("blog_articles_canonical_url_idx").on(table.canonicalUrl),
    publishedIdx: index("blog_articles_published_idx").on(table.isPublished),
    viewCountIdx: index("blog_articles_view_count_idx").on(table.viewCount),
  }
});

// Create insertion schemas and types
export const insertStudySchema = createInsertSchema(studies).omit({ id: true, createdAt: true, lastModified: true });
export const insertCategorySchema = createInsertSchema(categories).omit({ id: true, createdAt: true });
export const insertNewsletterSchema = createInsertSchema(newsletters).omit({ id: true, createdAt: true });
export const insertContactSchema = createInsertSchema(contactMessages).omit({ id: true, createdAt: true });
export const insertBlogArticleSchema = createInsertSchema(blogArticles).omit({ id: true, createdAt: true, updatedAt: true, viewCount: true });
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true, updatedAt: true });
export const insertUserPreferencesSchema = createInsertSchema(userPreferences).omit({ id: true, createdAt: true, updatedAt: true });
export const insertSearchHistorySchema = createInsertSchema(searchHistory).omit({ id: true, searchDate: true });
export const insertNotificationSchema = createInsertSchema(notifications).omit({ id: true, createdAt: true });
export const insertUserStudyInteractionSchema = createInsertSchema(userStudyInteractions).omit({ createdAt: true });
export const insertUserBlogInteractionSchema = createInsertSchema(userBlogInteractions).omit({ createdAt: true });
export const insertEducationalResourceSchema = createInsertSchema(educationalResources).omit({ id: true, createdAt: true, updatedAt: true, viewCount: true });
export const insertGlossaryTermSchema = createInsertSchema(glossaryTerms).omit({ id: true, createdAt: true, updatedAt: true });
export const insertFaqItemSchema = createInsertSchema(faqItems).omit({ id: true, createdAt: true, updatedAt: true });
export const insertStudyCollectionSchema = createInsertSchema(studyCollections).omit({ id: true, createdAt: true, updatedAt: true });
export const insertCollectionStudySchema = createInsertSchema(collectionStudies).omit({ addedAt: true });
export const insertStudyReviewQueueSchema = createInsertSchema(studyReviewQueue).omit({ 
  id: true, 
  savedAt: true, 
  reviewedAt: true, 
  createdAt: true 
});
export const insertSeoMetadataSchema = createInsertSchema(seoMetadata).omit({ 
  id: true, 
  createdAt: true,
  updatedAt: true
});

// Types for insertion
export type InsertStudy = z.infer<typeof insertStudySchema>;
export type InsertCategory = z.infer<typeof insertCategorySchema>;
export type InsertNewsletter = z.infer<typeof insertNewsletterSchema>;
export type InsertContact = z.infer<typeof insertContactSchema>;
export type InsertBlogArticle = z.infer<typeof insertBlogArticleSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertUserPreferences = z.infer<typeof insertUserPreferencesSchema>;
export type InsertSearchHistory = z.infer<typeof insertSearchHistorySchema>;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type InsertUserStudyInteraction = z.infer<typeof insertUserStudyInteractionSchema>;
export type InsertUserBlogInteraction = z.infer<typeof insertUserBlogInteractionSchema>;
export type InsertEducationalResource = z.infer<typeof insertEducationalResourceSchema>;
export type InsertGlossaryTerm = z.infer<typeof insertGlossaryTermSchema>;
export type InsertFaqItem = z.infer<typeof insertFaqItemSchema>;
export type InsertStudyCollection = z.infer<typeof insertStudyCollectionSchema>;
export type InsertCollectionStudy = z.infer<typeof insertCollectionStudySchema>;
export type InsertStudyReviewQueue = z.infer<typeof insertStudyReviewQueueSchema>;
export type InsertSeoMetadata = z.infer<typeof insertSeoMetadataSchema>;

// Types for selection
export type Study = typeof studies.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Newsletter = typeof newsletters.$inferSelect;
export type BlogArticle = typeof blogArticles.$inferSelect;
export type User = typeof users.$inferSelect;
export type UserPreferences = typeof userPreferences.$inferSelect;
export type SearchHistory = typeof searchHistory.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type UserStudyInteraction = typeof userStudyInteractions.$inferSelect;
export type UserBlogInteraction = typeof userBlogInteractions.$inferSelect;
export type EducationalResource = typeof educationalResources.$inferSelect;
export type GlossaryTerm = typeof glossaryTerms.$inferSelect;
export type FaqItem = typeof faqItems.$inferSelect;
export type StudyCollection = typeof studyCollections.$inferSelect;
export type CollectionStudy = typeof collectionStudies.$inferSelect;
export type StudyReviewQueue = typeof studyReviewQueue.$inferSelect;
export type SeoMetadata = typeof seoMetadata.$inferSelect;

// Chat conversations table schema
export const conversations = pgTable("conversations", {
  id: serial("id").primaryKey(),
  userId: text("user_id").references(() => users.id),
  title: text("title").default("New Conversation"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Chat messages table schema
export const chatMessages = pgTable("chat_messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id").notNull().references(() => conversations.id),
  role: varchar("role", { length: 20 }).notNull(), // 'user' or 'assistant'
  content: text("content").notNull(),
  timestamp: timestamp("timestamp").notNull().defaultNow(),
});

// Chat feedback table schema
export const chatFeedback = pgTable("chat_feedback", {
  id: serial("id").primaryKey(),
  messageId: integer("message_id").notNull().references(() => chatMessages.id),
  userId: text("user_id").references(() => users.id),
  rating: integer("rating").notNull(), // 1 (thumbs down) or 5 (thumbs up)
  comment: text("comment"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Popular questions table schema
export const popularQuestions = pgTable("popular_questions", {
  id: serial("id").primaryKey(),
  question: text("question").notNull().unique(),
  category: text("category").notNull(),
  displayOrder: integer("display_order").default(0),
  clickCount: integer("click_count").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Create insertion schemas for chat tables
export const insertConversationSchema = createInsertSchema(conversations).omit({ id: true, createdAt: true, updatedAt: true });
export const insertChatMessageSchema = createInsertSchema(chatMessages).omit({ id: true, timestamp: true });
export const insertChatFeedbackSchema = createInsertSchema(chatFeedback).omit({ id: true, createdAt: true });
export const insertPopularQuestionSchema = createInsertSchema(popularQuestions).omit({ id: true, clickCount: true, createdAt: true });

// Types for chat tables
export type Conversation = typeof conversations.$inferSelect;
export type ChatMessage = typeof chatMessages.$inferSelect;
export type ChatFeedback = typeof chatFeedback.$inferSelect;
export type PopularQuestion = typeof popularQuestions.$inferSelect;
export type InsertConversation = z.infer<typeof insertConversationSchema>;
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
export type InsertChatFeedback = z.infer<typeof insertChatFeedbackSchema>;
export type InsertPopularQuestion = z.infer<typeof insertPopularQuestionSchema>;

// Keyword monitoring tables
export const keywords = pgTable("keywords", {
  id: serial("id").primaryKey(),
  term: text("term").notNull(),
  category: text("category").default("general").notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  lastSearched: timestamp("last_searched"),
  matchCount: integer("match_count").default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const excludedKeywords = pgTable("excluded_keywords", {
  id: serial("id").primaryKey(),
  term: text("term").notNull(),
  reason: text("reason"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const keywordGroups = pgTable("keyword_groups", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const keywordGroupMappings = pgTable("keyword_group_mappings", {
  id: serial("id").primaryKey(),
  keywordId: integer("keyword_id").references(() => keywords.id, { onDelete: "cascade" }).notNull(),
  groupId: integer("group_id").references(() => keywordGroups.id, { onDelete: "cascade" }).notNull(),
});

export const monitorSchedule = pgTable("monitor_schedule", {
  id: serial("id").primaryKey(),
  enabled: boolean("enabled").default(false).notNull(),
  frequency: text("frequency").default("daily").notNull(),
  time: text("time").default("00:00").notNull(),
  days: text("days").array(),
  sources: text("sources").array(),
  lastRun: timestamp("last_run"),
  nextRun: timestamp("next_run"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const monitorResults = pgTable("monitor_results", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  abstract: text("abstract"),
  authors: text("authors"),
  journal: text("journal"),
  publishDate: text("publish_date"),
  doi: text("doi"),
  url: text("url"),
  matchedKeywords: text("matched_keywords").array(),
  status: text("status").default("pending").notNull(),
  source: text("source").notNull(),
  foundAt: timestamp("found_at").defaultNow().notNull(),
  reviewedBy: text("reviewed_by"),
  reviewedAt: timestamp("reviewed_at"),
  notes: text("notes"),
});

// Create insertion schemas for keyword monitoring
export const insertKeywordSchema = createInsertSchema(keywords).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true, 
  lastSearched: true,
  matchCount: true
});
export const insertExcludedKeywordSchema = createInsertSchema(excludedKeywords).omit({ id: true, createdAt: true });
export const insertKeywordGroupSchema = createInsertSchema(keywordGroups).omit({ id: true, createdAt: true });
export const insertKeywordGroupMappingSchema = createInsertSchema(keywordGroupMappings).omit({ id: true });
export const insertMonitorResultSchema = createInsertSchema(monitorResults).omit({ 
  id: true, 
  foundAt: true, 
  reviewedAt: true 
});
export const insertMonitorScheduleSchema = createInsertSchema(monitorSchedule).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  lastRun: true,
  nextRun: true
});

// Types for keyword monitoring
export type Keyword = typeof keywords.$inferSelect;
export type ExcludedKeyword = typeof excludedKeywords.$inferSelect;
export type KeywordGroup = typeof keywordGroups.$inferSelect;
export type KeywordGroupMapping = typeof keywordGroupMappings.$inferSelect;
export type MonitorSchedule = typeof monitorSchedule.$inferSelect;
export type MonitorResult = typeof monitorResults.$inferSelect;
export type InsertKeyword = z.infer<typeof insertKeywordSchema>;
export type InsertExcludedKeyword = z.infer<typeof insertExcludedKeywordSchema>;
export type InsertKeywordGroup = z.infer<typeof insertKeywordGroupSchema>;
export type InsertKeywordGroupMapping = z.infer<typeof insertKeywordGroupMappingSchema>;
export type InsertMonitorSchedule = z.infer<typeof insertMonitorScheduleSchema>;
export type InsertMonitorResult = z.infer<typeof insertMonitorResultSchema>;

// ===== AUTOMATED TAGGING SYSTEM =====

// Tags table - stores all available tags
export const tags = pgTable("tags", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  category: text("category").notNull(), // health_condition, body_system, methodology, outcome, etc.
  color: text("color"), // For UI display
  usageCount: integer("usage_count").default(0),
  isSystemGenerated: boolean("is_system_generated").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Study-tag relationships (many-to-many)
export const studyTags = pgTable("study_tags", {
  id: serial("id").primaryKey(),
  studyId: integer("study_id").references(() => studies.id, { onDelete: "cascade" }).notNull(),
  tagId: integer("tag_id").references(() => tags.id, { onDelete: "cascade" }).notNull(),
  confidence: integer("confidence").default(100), // AI confidence score 0-100
  source: text("source").notNull(), // 'title', 'abstract', 'keywords', 'content', 'manual'
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueStudyTag: unique().on(table.studyId, table.tagId),
    studyIdx: index("study_tags_study_idx").on(table.studyId),
    tagIdx: index("study_tags_tag_idx").on(table.tagId),
  }
});

// Tag categories for organization
export const tagCategories = pgTable("tag_categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  color: text("color"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Tag synonyms for better matching
export const tagSynonyms = pgTable("tag_synonyms", {
  id: serial("id").primaryKey(),
  tagId: integer("tag_id").references(() => tags.id, { onDelete: "cascade" }).notNull(),
  synonym: text("synonym").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueSynonym: unique().on(table.tagId, table.synonym),
  }
});

// Create insertion schemas for tagging system
export const insertTagSchema = createInsertSchema(tags).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true,
  usageCount: true
});
export const insertStudyTagSchema = createInsertSchema(studyTags).omit({ 
  id: true, 
  createdAt: true 
});
export const insertTagCategorySchema = createInsertSchema(tagCategories).omit({ 
  id: true, 
  createdAt: true 
});
export const insertTagSynonymSchema = createInsertSchema(tagSynonyms).omit({ 
  id: true, 
  createdAt: true 
});

// Types for tagging system
export type Tag = typeof tags.$inferSelect;
export type StudyTag = typeof studyTags.$inferSelect;
export type TagCategory = typeof tagCategories.$inferSelect;
export type TagSynonym = typeof tagSynonyms.$inferSelect;
export type InsertTag = z.infer<typeof insertTagSchema>;
export type InsertStudyTag = z.infer<typeof insertStudyTagSchema>;
export type InsertTagCategory = z.infer<typeof insertTagCategorySchema>;
export type InsertTagSynonym = z.infer<typeof insertTagSynonymSchema>;

// ===== SCIENTIFIC ARTICLES TABLE =====
// For longer, more detailed scientific content

export const scientificArticles = pgTable("scientific_articles", {
  id: serial("id").primaryKey(),
  studyId: integer("study_id").notNull().references(() => studies.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  articleType: text("article_type").notNull(), // 'comprehensive_review', 'clinical_applications'
  content: text("content").notNull(), // 2000-3000 words of detailed content
  summary: text("summary").notNull(), // Executive summary
  abstract: text("abstract"), // Formal scientific abstract
  introduction: text("introduction"), // Detailed introduction section
  methodology: text("methodology"), // Methodology analysis
  results: text("results"), // Results discussion
  discussion: text("discussion"), // In-depth discussion
  conclusion: text("conclusion"), // Scientific conclusion
  references: text("references").array(), // List of references/citations
  keywords: text("keywords").array(), // Scientific keywords for indexing
  authors: text("authors"), // Article authors (can differ from study authors)
  readingLevel: text("reading_level").default("8th-10th grade"), // Target reading level
  wordCount: integer("word_count").notNull(),
  readingTime: integer("reading_time").notNull(), // Estimated reading time in minutes
  
  // SEO fields
  metaTitle: text("meta_title"),
  metaDescription: text("meta_description"),
  canonicalUrl: text("canonical_url"),
  
  // Media fields
  imageUrl: text("image_url"),
  imageAlt: text("image_alt"),
  figures: text("figures").array(), // Scientific figures/charts
  figuresCaptions: text("figures_captions").array(),
  
  // Publishing fields
  isPublished: boolean("is_published").default(false),
  publishedAt: timestamp("published_at"),
  viewCount: integer("view_count").default(0),
  
  // Quality and review
  peerReviewed: boolean("peer_reviewed").default(false),
  reviewedBy: text("reviewed_by"),
  reviewNotes: text("review_notes"),
  qualityScore: integer("quality_score"), // 0-100 quality score
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Create insertion schema for scientific articles
export const insertScientificArticleSchema = createInsertSchema(scientificArticles).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  viewCount: true,
  publishedAt: true
});

// Types for scientific articles
export type ScientificArticle = typeof scientificArticles.$inferSelect;
export type InsertScientificArticle = z.infer<typeof insertScientificArticleSchema>;

// Study category types
export type StudyCategory = typeof studyCategories.$inferSelect;
export type InsertStudyCategory = typeof studyCategories.$inferInsert;
