import OpenAI from "openai";
import { BlogArticle, Study } from "@shared/schema";

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// Available suggestion types
export type SuggestionType =
  | "improve"
  | "expand"
  | "simplify"
  | "add_examples"
  | "add_research_context"
  | "elon_style"
  | "add_conclusion";

/**
 * Generate content suggestion for a blog article
 * @param blog Blog article to generate suggestion for
 * @param type Type of suggestion to generate
 * @param selectedContent Optional selected content to focus on
 * @param relatedStudy Optional related study for additional context
 * @returns Suggested content
 */
export async function generateContentSuggestion(
  blog: BlogArticle,
  type: SuggestionType,
  selectedContent?: string,
  relatedStudy?: Study,
): Promise<string> {
  try {
    // Get content to process - either selected content or full content
    const contentToProcess = selectedContent || blog.content;

    // Strip HTML tags for processing
    const plainContent = contentToProcess.replace(/<[^>]*>?/gm, "");

    // Generate prompt based on suggestion type
    const prompt = generatePromptForSuggestion(
      blog,
      plainContent,
      type,
      relatedStudy,
    );

    // Call OpenAI API
    const response = await openai.chat.completions.create({
      model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
      messages: [
        {
          role: "system",
          content:
            "You are an expert scientific blog writer specializing in hydrogen research. Your task is to help improve blog content while maintaining scientific accuracy.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 1000,
    });

    // Extract and return suggestion
    const suggestion = response.choices[0].message.content;

    if (!suggestion) {
      throw new Error("No suggestion generated by API");
    }

    return suggestion;
  } catch (error) {
    console.error("Error generating content suggestion:", error);
    throw error;
  }
}

/**
 * Generate AI prompt based on suggestion type
 */
function generatePromptForSuggestion(
  blog: BlogArticle,
  contentText: string,
  type: SuggestionType,
  relatedStudy?: Study,
): string {
  // Base context from blog metadata
  const readingLevel = blog.readingLevel || "6th";
  const articleType = blog.articleType || "manual";

  // Add study context if available
  let studyContext = "";
  if (relatedStudy) {
    studyContext = `
    This blog is related to the following research study: 
    Title: ${relatedStudy.title}
    Abstract: ${relatedStudy.abstract}
    Methods: ${relatedStudy.methods || "Not available"}
    Results: ${relatedStudy.results || "Not available"}
    Conclusion: ${relatedStudy.conclusion || "Not available"}
    `;
  }

  // Base prompt template
  let promptTemplate = `
  I need help with a blog article about hydrogen research.
  
  Blog Title: ${blog.title}
  Blog Summary: ${blog.summary.replace(/<[^>]*>?/gm, "")}
  Current Content: ${contentText}
  Reading Level: ${readingLevel}
  Article Type: ${articleType}
  
  ${studyContext}
  `;

  // Add specific instructions based on suggestion type
  switch (type) {
    case "improve":
      promptTemplate += `
      Please improve this content while maintaining the same meaning and scientific accuracy. 
      Focus on making the writing clearer, more engaging, and easier to understand at a ${readingLevel} reading level.
      Return only the improved content without explanations.
      `;
      break;

    case "expand":
      promptTemplate += `
      Please expand this content with additional relevant information. 
      Add more details, explanations, or background on the hydrogen research discussed.
      Maintain scientific accuracy and a ${readingLevel} reading level.
      Return only the expanded content without explanations.
      `;
      break;

    case "simplify":
      promptTemplate += `
      Please simplify this content to make it more accessible to a general audience.
      Reduce technical jargon while maintaining scientific accuracy.
      Target a ${readingLevel} reading level.
      Return only the simplified content without explanations.
      `;
      break;

    case "add_examples":
      promptTemplate += `
      Please add 2-3 practical examples or applications that illustrate the concepts discussed in this content.
      Make these examples relevant to everyday life or practical applications of hydrogen research.
      Maintain a ${readingLevel} reading level.
      Return only the original content with the new examples seamlessly integrated.
      `;
      break;

    case "add_research_context":
      promptTemplate += `
      Please add more scientific context to this content, including:
      - Brief mentions of related research
      - Scientific consensus on the topic
      - Potential future research directions
      
      Maintain scientific accuracy and a ${readingLevel} reading level.
      Return only the enhanced content without explanations.
      `;
      break;

    case "elon_style":
      promptTemplate += `
      Please rewrite this content in the style of Elon Musk explaining complex science:
      - Use simple, direct language
      - Include analogies that make complex concepts relatable
      - Add some excitement about the future implications
      - Maintain a conversational, slightly quirky tone
      - Emphasize revolutionary potential of the research
      
      Maintain scientific accuracy and a ${readingLevel} reading level.
      Return only the rewritten content without explanations.
      `;
      break;

    case "add_conclusion":
      promptTemplate += `
      Please add a strong concluding paragraph to this content that:
      - Summarizes the key points
      - Emphasizes the significance of the hydrogen research
      - Includes a brief look at future implications
      - Ends with a thought-provoking statement
      
      Maintain scientific accuracy and a ${readingLevel} reading level.
      Return only the full content with the new conclusion seamlessly integrated.
      `;
      break;

    default:
      promptTemplate += `
      Please review and improve this content while maintaining scientific accuracy.
      Focus on clarity, engagement, and accessibility at a ${readingLevel} reading level.
      Return only the improved content without explanations.
      `;
  }

  return promptTemplate;
}

/**
 * Generate title suggestions for a blog based on its content
 * @param blog Blog article to generate title suggestions for
 * @returns Array of title suggestions
 */
export async function generateTitleSuggestions(
  blog: BlogArticle,
): Promise<string[]> {
  try {
    // Strip HTML tags from content and summary
    const plainContent = blog.content
      .replace(/<[^>]*>?/gm, "")
      .substring(0, 1000);
    const plainSummary = blog.summary.replace(/<[^>]*>?/gm, "");

    // Generate prompt for title suggestions
    const prompt = `
    Please suggest 5 engaging and scientifically accurate titles for a blog article about hydrogen research.
    
    Current Title: ${blog.title}
    Blog Summary: ${plainSummary}
    Blog Content Excerpt: ${plainContent}
    
    The titles should be:
    - Engaging and attention-grabbing
    - Scientifically accurate
    - Appropriate for a research audience
    - Each less than 100 characters
    - Each unique in approach/angle
    
    Format your response as a numbered list with just the titles (1. Title one, 2. Title two, etc).
    `;

    // Call OpenAI API
    const response = await openai.chat.completions.create({
      model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
      messages: [
        {
          role: "system",
          content:
            "You are an expert scientific editor with experience in crafting engaging titles for research content.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.8,
      max_tokens: 500,
    });

    // Extract and return title suggestions
    const suggestionsText = response.choices[0].message.content || "";

    // Parse the numbered list of suggestions
    const suggestions = suggestionsText
      .split(/\d+\./)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .slice(0, 5); // Ensure we have max 5 suggestions

    return suggestions;
  } catch (error) {
    console.error("Error generating title suggestions:", error);
    throw error;
  }
}
